### PR TITLE
Run examples in docs

### PR DESCRIPTION
**Pull request by baggepinnen**
This PR is a step towards solving #1570 , there are a few more files to modify but this PR can be a first step.
I added the `strict` keyword to `makedocs` to make sure docs build fails for certain kinds of errors. There are more alternatives that could be added here.

### CODE REVIEW

**Comment by baggepinnen** [comment]
Currently docs build fails with 
```julia
ERROR: LoadError: AssertionError: latexify does not support objects of type Connection.
Stacktrace:
  [1] _latexraw(args::Connection; kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:cdot, :env), Tuple{Bool, Symbol}}})
    @ Latexify ~/.julia/packages/Latexify/wO7r4/src/latexraw.jl:109
  [2] process_latexify(args::Num; kwargs::Base.Pairs{Symbol, Symbol, Tuple{Symbol}, NamedTuple{(:env,), Tuple{Symbol}}})
    @ Latexify ~/.julia/packages/Latexify/wO7r4/src/latexify_function.jl:25
  [3] #latexraw#6
    @ ~/.julia/packages/Latexify/wO7r4/src/latexraw.jl:58 [inlined]
```
https://github.com/SciML/ModelingToolkit.jl/runs/6406200523?check_suite_focus=true#step:5:369
@YingboMa  you don't happen to know how to fix that?

**Comment by YingboMa** [comment]
https://github.com/JuliaSymbolics/Symbolics.jl/pull/597

**Comment by baggepinnen** [comment]
The next error appears to be 
```
┌ Error: failed to run `@example` block in src/tutorials/tearing_parallelism.md:165-171
│ ```@example tearing
│ using ModelingToolkit.BipartiteGraphs
│ ts = TearingState(expand_connections(big_rc))
│ inc_org = BipartiteGraphs.incidence_matrix(ts.graph)
│ blt_org = StructuralTransformations.sorted_incidence_matrix(big_rc, only_algeqs=true, only_algvars=true)
│ blt_reduced = StructuralTransformations.sorted_incidence_matrix(sys, only_algeqs=true, only_algvars=true)
│ ```
│   value = type TearingState has no field graph
```

**Comment by ChrisRackauckas** [comment]
I noticed you missed some.

https://github.com/SciML/ModelingToolkit.jl/blob/master/docs/src/tutorials/optimization.md
https://mtk.sciml.ai/stable/tutorials/nonlinear/

etc.

**Comment by baggepinnen** [comment]
Yes
> This PR is a step towards solving https://github.com/SciML/ModelingToolkit.jl/issues/1570 , there are a few more files to modify but this PR can be a first step.

There are quite a few things Documenter can be made to check for us and error if we fail:
- autodocs_block
- cross_references
- docs_block
- doctest
- eval_block
- example_block
- footnote
- linkcheck
- meta_block
- missing_docs
- parse_error
- setup_block

I think all of those make sense to enable, save for possible `missing_docs` which could perhaps be a longer-term goal.

**Pull request merged**
