### PR TITLE
fix: fix flattening in `complete`

### PR DESCRIPTION
**Pull request by AayushSabharwal**
The old implementation broke Catalyst, but it wasn't detected due to differing BifurcationKit compats preventing tests from running.

## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Extension test failing? Seems unrelated though.

**Comment by AayushSabharwal** [comment]
Huh, weird, it only fails on lts.

**Comment by ChrisRackauckas** [comment]
Must be an alternative solution or something, just choosing the wrong root?

**Comment by AayushSabharwal** [comment]
Nope, it's a bug. `x = 2` is an invalid root because it occurs in the denominator, but I forgot to add an `abs` in the check so it accepts `2 - 2e-8` but rejects `2 + 2e-8`.

**Pull request merged**
