### PR TITLE
Accelerate connection sets merging with union-find

### PR DESCRIPTION
**Pull request by YingboMa**
Baseline:
```julia
julia> @time run_and_time_julia!(ss_times, times, max_sizes, 1, 100)
  0.960393 seconds (8.15 M allocations: 540.022 MiB, 4.47% gc time)
0.888558584

julia> @time run_and_time_julia!(ss_times, times, max_sizes, 1, 200)
  2.593054 seconds (17.95 M allocations: 1.131 GiB, 3.75% gc time)
2.465012458

julia> @time run_and_time_julia!(ss_times, times, max_sizes, 1, 300)
  5.065673 seconds (29.41 M allocations: 1.821 GiB, 5.90% gc time)
4.861177375
```

PR:
```julia
julia> @time run_and_time_julia!(ss_times, times, max_sizes, 1, 100);
  0.748587 seconds (7.61 M allocations: 513.135 MiB, 7.15% gc time)

julia> @time run_and_time_julia!(ss_times, times, max_sizes, 1, 200);
  1.681521 seconds (15.75 M allocations: 1.027 GiB, 7.71% gc time)

julia> @time run_and_time_julia!(ss_times, times, max_sizes, 1, 300);
  2.931254 seconds (24.43 M allocations: 1.590 GiB, 11.97% gc time)
```

### CODE REVIEW

**Comment by YingboMa** [comment]
image
That's most the low hanging fruits in connection merging. Hashconsing and a more closed symbolic type would be the way to further speedup the front-end.

CC: @bowenszhu @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
bariess comes up a lot, is this RC circuit?

**Comment by YingboMa** [comment]
> bariess comes up a lot, is this RC circuit?

No, it's the thermal fluid model.

**Comment by ChrisRackauckas** [comment]
Oh, the better bariess is back on the menu?

**Review by chriselrod — APPROVED** [review]

**Comment by YingboMa** [comment]
image

> Oh, the better bariess is back on the menu?


I don't think so. Bareiss there is just a profile fluke. I ran the profile again and it disappeared. I must have forgotten to clear the profile cache before taking the screenshot.

**Comment by YingboMa** [comment]
The test failure seems unrelated.

**Comment by YingboMa** [comment]
@ChrisRackauckas the test failure seems to be due to the printing change.

**Comment by ChrisRackauckas** [comment]
I fixed that on master? This must've branched from an earlier master.

**Pull request merged**
