### PR TITLE
Symbolics / SymbolicUtils / TermInterface bump

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Currently blocked on https://github.com/Vaibhavdixit02/SymbolicAnalysis.jl/pull/43. @Vaibhavdixit02 can we get to a solution or at least start a process on this today?

**Comment by ChrisRackauckas** [comment]
🤞

**Comment by ChrisRackauckas** [comment]
```julia
equality constraint: Error During Test at /home/runner/work/ModelingToolkit.jl/ModelingToolkit.jl/test/optimizationsystem.jl:79
  Got exception outside of a @test
  MethodError: no method matching MathOptInterface.FileFormats.NL._NLExpr(::SymbolicUtils.BasicSymbolic{Real})
  
  Closest candidates are:
    MathOptInterface.FileFormats.NL._NLExpr(::Any, ::Any, ::Any, ::Any)
     @ MathOptInterface ~/.julia/packages/MathOptInterface/jqDoD/src/FileFormats/NL/NLExpr.jl:293
    MathOptInterface.FileFormats.NL._NLExpr(::Bool, ::Vector{Union{Float64, Int64, MathOptInterface.VariableIndex}}, ::Dict{MathOptInterface.VariableIndex, Float64}, ::Float64)
     @ MathOptInterface ~/.julia/packages/MathOptInterface/jqDoD/src/FileFormats/NL/NLExpr.jl:293
    MathOptInterface.FileFormats.NL._NLExpr(::MathOptInterface.VariableIndex)
     @ MathOptInterface ~/.julia/packages/MathOptInterface/jqDoD/src/FileFormats/NL/NLExpr.jl:306
    ...
  
  Stacktrace:
    [1] copy_to(dest::MathOptInterface.FileFormats.NL.Model, model::MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}})
      @ MathOptInterface.FileFormats.NL ~/.julia/packages/MathOptInterface/jqDoD/src/FileFormats/NL/NL.jl:267
    [2] copy_to
      @ ~/.julia/packages/AmplNLWriter/XKNTn/src/AmplNLWriter.jl:277 [inlined]
    [3] optimize!
      @ ~/.julia/packages/MathOptInterface/jqDoD/src/MathOptInterface.jl:121 [inlined]
    [4] optimize!(m::MathOptInterface.Utilities.CachingOptimizer{AmplNLWriter.Optimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}})
      @ MathOptInterface.Utilities ~/.julia/packages/MathOptInterface/jqDoD/src/Utilities/cachingoptimizer.jl:321
    [5] __solve(prob::SciMLBase.OptimizationProblem{true, SciMLBase.OptimizationFunction{true, SciMLBase.NoAD, ModelingToolkit.var"#__f#1039"{RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋arg1, :ˍ₋arg2), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0x8ef3fb4c, 0x7ff2c55e, 0x2ca7691a, 0x81e3429d, 0xb23868a8), Nothing}}, Nothing, Nothing, Nothing, RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋out, :ˍ₋arg1, :ˍ₋arg2), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0x8f658d66, 0x10e1a33c, 0x36fa5f09, 0xb65ed71a, 0x8f0f0b23), Nothing}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, ModelingToolkit.ObservedFunctionCache{ModelingToolkit.OptimizationSystem}, SymbolicUtils.BasicSymbolic{Real}, Vector{Union{Symbolics.Equation, Symbolics.Inequality}}, ModelingToolkit.OptimizationSystem, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing}, Vector{Float64}, ModelingToolkit.MTKParameters{Vector{Float64}, StaticArraysCore.SizedVector{0, Any, Vector{Any}}, Tuple{}, Tuple{}}, Nothing, Nothing, BitVector, Vector{Float64}, Vector{Float64}, Nothing, @Kwargs{}}, opt::AmplNLWriter.Optimizer; maxiters::Nothing, maxtime::Nothing, abstol::Nothing, reltol::Nothing, kwargs::@Kwargs{})
```

@Vaibhavdixit02 I don't see how this is related. Is there some other change that is getting mixed up in this? Some unreleased MOI change that is now just popping up?

**Comment by Vaibhavdixit02** [comment]
Seems to not be reproducible with master, the compact on Symbolics was making it use a very old OptimizationMOI, created a release rerunning it should hopefully just make it go away

**Review by Vaibhavdixit02 — APPROVED** [review]
LGTM

**Pull request merged**
