### PR TITLE
Overload `propertynames` and add `@nonamespace`

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Where is `@nonamespace` used?

**Comment by YingboMa** [comment]
It's not used, but could be helpful if the user define models hierarchically, and want to share a variable across two parallel level models.

**Comment by ChrisRackauckas** [comment]
Then if it's user-facing, it should get a user-facing docstring. Or at least, a sentence above that which describes what it does and be put into the docs. Right now it looks like an internal.

**Comment by YingboMa** [comment]
Yeah, I haven't decided how this should be used yet, so I haven't documented it yet. I think it will be helpful later when we implement inheritance, so I added it preemptively.

**Comment by ChrisRackauckas** [comment]
alright.

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
