### PR TITLE
Jump problem kwarg fix

### PR DESCRIPTION
**Pull request by isaacsas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Travis is back 🤦

**Comment by ChrisRackauckas** [comment]
But on the wrong website

**Comment by isaacsas** [comment]
Doh

**Comment by isaacsas** [comment]
Can we get a new release now to push out these last two PRs? Thanks!

**Comment by isaacsas** [comment]
NV, missed you’re already on it.

**Pull request merged**
