### PR TITLE
Add connections to NonlinearSystem

### LINKED ISSUE #1442: NonlinearSystem fails with connection equations since v8
Because non linear equations are rewritten to canonical form, the systems that contain connection equations fail. 
MWE : 
```julia
using ModelingToolkit

@connector function connector(;name::Symbol)
    sts = @variables x
    NonlinearSystem(Equation[], sts, [], name = name)
end

@named c1 = connector()
@named c2 = connector()

eqs_con = [
    connect(c1, c2)
]

@named ns_con = NonlinearSystem(eqs_con, [], [])
```
```julia
ERROR: LoadError: MethodError: no method matching -(::Connection, ::Connection)
Closest candidates are:
  -(::MultivariatePolynomials.RationalPoly, ::Any) at \.julia\packages\MultivariatePolynomials\JG6mC\src\rational.jl:59
  -(::ChainRulesCore.AbstractThunk, ::Any) at \.julia\packages\ChainRulesCore\uxrij\src\tangent_types\thunks.jl:32
  -(::MultivariatePolynomials.AbstractPolynomialLike, ::Any) at \.julia\packages\MultivariatePolynomials\JG6mC\src\operators.jl:45
  ...
Stacktrace:
 [1] (::ModelingToolkit.var"#412#415")(x::Equation)
   @ ModelingToolkit .\none:0
 [2] iterate
   @ .\generator.jl:47 [inlined]
 [3] collect(itr::Base.Generator{Vector{Equation}, ModelingToolkit.var"#412#415"})
   @ Base .\array.jl:724
 [4] NonlinearSystem(eqs::Vector{Equation}, states::Vector{Any}, ps::Vector{Any}; observed::Vector{Any}, name::Symbol, default_u0::Dict{Any, Any}, default_p::Dict{Any, Any}, defaults::Dict{Any, Any}, systems::Vector{NonlinearSystem}, connector_type::Nothing, continuous_events::Nothing, checks::Bool)
   @ ModelingToolkit \.julia\packages\ModelingToolkit\zjJ83\src\systems\nonlinear\nonlinearsystem.jl:83
 [5] top-level scope
   @ Untitled-1:16
in expression starting at Untitled-1:16
```

### PR DESCRIPTION
**Pull request by Tred0**
This PR intends to fix #1442 

The nonlinear system is created. However `expand_connections` is missing stream connections.

This a small example to illustrate the issue : 
```julia
using ModelingToolkit

@connector function port(;name::Symbol)
    sts = @variables P Q [connect = Flow] H [connect = Stream]
    
    NonlinearSystem(Equation[], sts, [];
        name = name,
        defaults = [
            P => 1.01325e5,
            Q => 10.0,
            H => 1e5])
end

function pipe(;name::Symbol, h_loss = 1e4, dp = 2e3)
    @named c_in = port()
    @named c_out = port()
    ps = @parameters h_loss = h_loss dp = dp

    eqs = [
        c_in.H ~ c_out.H + h_loss
        c_in.Q ~ c_out.Q
        c_in.P ~ c_out.P + dp
    ]
    
    NonlinearSystem(eqs, [], ps;
        name = name, systems = [c_in, c_out])
end

function source(;name, P0= 1e5, Q0 = 10., H0 = 1e5)
    @named c = port()
    ps = @parameters P0 = P0 Q0 =Q0 H0 = H0

    eqs = [
        c.P ~ P0
        c.Q ~ Q0
        c.H ~ H0
    ]

    NonlinearSystem(eqs, [], ps;
        name = name, systems = [c])
end


@named ms = source()
@named mp = pipe()

eqs_con =[
    connect(ms.c, mp.c_in)
]

@named my_sys = NonlinearSystem(eqs_con, [], []; systems = [ms, mp])

expand_connections(my_sys) |> equations
```
It gives 
```julia
8-element Vector{Equation}:
 0 ~ ms₊P0 - ms₊c₊P
 0 ~ ms₊Q0 - ms₊c₊Q
 0 ~ ms₊H0 - ms₊c₊H
 0 ~ mp₊c_out₊H + mp₊h_loss - mp₊c_in₊H
 0 ~ mp₊c_out₊Q - mp₊c_in₊Q
 0 ~ mp₊c_out₊P + mp₊dp - mp₊c_in₊P    
 ms₊c₊P ~ mp₊c_in₊P
 0 ~ mp₊c_in₊Q + ms₊c₊Q
```
which is missing H equations

### CODE REVIEW

**Comment by YingboMa** [comment]
That's expected. Stream connectors only generate equations for outside connects.

**Review by YingboMa — APPROVED** [review]
LGTM

**Comment by Tred0** [comment]
Thank you. How would you define an outside connection ?

**Comment by YingboMa** [comment]
I think in this case, you want to use `instream` manually. You can get some inspirations from https://github.com/SciML/ModelingToolkit.jl/blob/ef6c4bf01acd4e85cf30b6058ff4b97073be0261/test/stream_connectors.jl

**Pull request merged**
