### PR TITLE
Test master

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@AayushSabharwal is this what you were talking about the other day? https://github.com/SciML/ModelingToolkit.jl/actions/runs/11193882959/job/31119719069?pr=3094#step:6:1125

**Comment by hersle** [comment]
It broke from the [3rd to the 1st commit between Sept. 27-28](https://github.com/SciML/ModelingToolkit.jl/commits/master/?since=2024-09-27&until=2024-09-28), where only DiffEqCallbacks was bumped to v4. Reverting to DiffEqCallbacks v3 does not fix it on my machine, so I think the cause is external. Maybe something solver-related in [this test call](https://github.com/SciML/ModelingToolkit.jl/blob/0916a02afd7944d96f20d22c7b65c475b74a68e5/test/structural_transformation/tearing.jl#L173-L177)?

**Comment by AayushSabharwal** [comment]
> @AayushSabharwal is this what you were talking about the other day?

Yes

> Maybe something solver-related in [this test call](https://github.com/SciML/ModelingToolkit.jl/blob/0916a02afd7944d96f20d22c7b65c475b74a68e5/test/structural_transformation/tearing.jl#L173-L177)?

That test call fails because it uses the tstops from the previous solve, which fails.

**Comment by hersle** [comment]
https://github.com/SciML/DiffEqBase.jl/commit/f870554bb1b8257f377e86702551a18d80f77be5 breaks the test.

**Comment by ChrisRackauckas** [comment]
Really? That's related????

**Comment by ChrisRackauckas** [comment]
Just decrease the tolerance, that's effectively random.

**Comment by hersle** [comment]
Yeah, it seems very sensitive to the tolerance. I just did checkout on some commits until this hit.

**Comment by hersle** [comment]
```julia
using Printf
for pow in range(-10, -3)
    for fac in range(1, 9)
        reltol = fac * 10.0^pow
        sol1 = solve(prob, RosShamp4(); reltol)
        @printf "reltol = %.1E -> %s\n" reltol sol1.retcode
    end
end
```
```
reltol = 1.0E-10 -> Unstable
reltol = 2.0E-10 -> Unstable
reltol = 3.0E-10 -> Success
reltol = 4.0E-10 -> Unstable
reltol = 5.0E-10 -> Unstable
reltol = 6.0E-10 -> Unstable
reltol = 7.0E-10 -> Unstable
reltol = 8.0E-10 -> Unstable
reltol = 9.0E-10 -> Unstable
reltol = 1.0E-09 -> Unstable
reltol = 2.0E-09 -> Unstable
reltol = 3.0E-09 -> Unstable
reltol = 4.0E-09 -> Unstable
reltol = 5.0E-09 -> Unstable
reltol = 6.0E-09 -> Unstable
reltol = 7.0E-09 -> Unstable
reltol = 8.0E-09 -> Unstable
reltol = 9.0E-09 -> Unstable
reltol = 1.0E-08 -> Unstable
reltol = 2.0E-08 -> Unstable
reltol = 3.0E-08 -> Unstable
reltol = 4.0E-08 -> Unstable
reltol = 5.0E-08 -> Unstable
reltol = 6.0E-08 -> Unstable
reltol = 7.0E-08 -> Unstable
reltol = 8.0E-08 -> Unstable
reltol = 9.0E-08 -> Unstable
reltol = 1.0E-07 -> Unstable
reltol = 2.0E-07 -> Unstable
reltol = 3.0E-07 -> Unstable
reltol = 4.0E-07 -> Unstable
reltol = 5.0E-07 -> Unstable
reltol = 6.0E-07 -> Unstable
reltol = 7.0E-07 -> Unstable
reltol = 8.0E-07 -> Unstable
reltol = 9.0E-07 -> Unstable
reltol = 1.0E-06 -> Unstable
reltol = 2.0E-06 -> Unstable
reltol = 3.0E-06 -> Unstable
reltol = 4.0E-06 -> Unstable
reltol = 5.0E-06 -> Unstable
reltol = 6.0E-06 -> Unstable
reltol = 7.0E-06 -> Success
reltol = 8.0E-06 -> Unstable
reltol = 9.0E-06 -> Success
reltol = 1.0E-05 -> Unstable
reltol = 2.0E-05 -> Success
reltol = 3.0E-05 -> Success
reltol = 4.0E-05 -> Unstable
reltol = 5.0E-05 -> Unstable
reltol = 6.0E-05 -> Success
reltol = 7.0E-05 -> Unstable
reltol = 8.0E-05 -> Unstable
reltol = 9.0E-05 -> Unstable
reltol = 1.0E-04 -> Success
reltol = 2.0E-04 -> Success
reltol = 3.0E-04 -> Success
reltol = 4.0E-04 -> Unstable
reltol = 5.0E-04 -> Success
reltol = 6.0E-04 -> Unstable
reltol = 7.0E-04 -> Success
reltol = 8.0E-04 -> Unstable
reltol = 9.0E-04 -> Success
reltol = 1.0E-03 -> Success
reltol = 2.0E-03 -> Success
reltol = 3.0E-03 -> Success
reltol = 4.0E-03 -> Success
reltol = 5.0E-03 -> Success
reltol = 6.0E-03 -> Success
reltol = 7.0E-03 -> Success
reltol = 8.0E-03 -> Success
reltol = 9.0E-03 -> Unstable
```

**Comment by AayushSabharwal** [comment]
I picked a tolerance from @hersle 's table above at the beginning of what looks like a relatively stable region

**Comment by AayushSabharwal** [comment]
Huh, that passed locally

**Comment by AayushSabharwal** [comment]
So far no luck in replicating any of the failures in `InterfaceI`

**Comment by hersle** [comment]
I got the feeling the test is not robust regardless, considering how https://github.com/SciML/DiffEqBase.jl/commit/f870554bb1b8257f377e86702551a18d80f77be5 breaks it. Maybe even machine-dependent floating point operations etc. play a role.

**Comment by AayushSabharwal** [comment]
That's possible, but how is it getting differently sized arrays given the tstops of the previous solve?

**Comment by AayushSabharwal** [comment]
Hmm, there's this warning:
```
┌ Warning: At t=0.6261972386805764, dt was forced below floating point epsilon 1.1102230246251565e-16, and step error estimate = 3.138704824490307. Aborting. There is either an error in your model specification or the true solution is unstable (or the true solution can not be represented in the precision of Float64).
└ @ SciMLBase ~/.julia/packages/SciMLBase/PTTHz/src/integrator_interface.jl:609
```
right before the failure. Maybe the first solve is failing on CI?

**Comment by hersle** [comment]
I think that's what causes it.

**Comment by AayushSabharwal** [comment]
I also fixed a failure in InterfaceII's dde tests, but it's failing differently now and is also not reproducing. This is really weird behavior

**Pull request merged**
