### PR TITLE
Support conditional statements in `@mtkmodel`

### PR DESCRIPTION
**Pull request by ven-k**
This PR adds support for
- Conditional default values
```julia
@mtkmodel A begin
    ...
    @parameters begin
        a = condition ? 1 : 0
    end
end
```
- Conditional equations and components inside the respective blocks
    - [x] Inside `@equations`
    - [x] Inside `@components`
    - [x] Inside `@parameters` and `@variables`
```julia
@mtkmodel A begin
    ...
    @components begin
       if condition1
            b = B()
       end
    end
    @equations begin
       if condition2
            a ~ 0
       end
    end
end
```
- If branch at top level
   - [x] Equations
   - [x] Components
   - [x] Parameters
```julia
@mtkmodel A begin
    ...
    if condition
        @components begin
             b = B()
        end
        @equations begin
                a ~ 0
        end
    end
end
```

- [x] Adds relevant docs.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Should we also generate events here or lower @YingboMa ?

**Comment by baggepinnen** [comment]
I guess it depends on whether `condition` is a structural parameter or a symbolic expression. It'd be nice to support both, since structural parameters are often used to determine which equations to include.

**Comment by ven-k** [comment]
Bump

**Comment by YingboMa** [comment]
The MTKStdlib failure looks real. Also, could you merge master back to this branch and run formatter?

**Comment by ven-k** [comment]
@YingboMa I've rebased and have fixed issues that threw error in MTKStdlib tests. This can be reviewed.

**Review by YingboMa — APPROVED** [review]
This looks really good!

**Pull request merged**
