### PR TITLE
rewrite nonlinear solve tutorial

### PR DESCRIPTION
**Pull request by ArnoStrouwen**
The jump from getting started to this tutorial is somewhat rough, since the macro interface can no longer be used.
A note which explains this and some further guidance has been added.

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
Can you fix the link check?

**Comment by ArnoStrouwen** [comment]
Failure unrelated, merge please.

**Comment by ChrisRackauckas** [comment]
@thazhemadam is there a reason this repo isn't getting suggestions from the formatter?

**Comment by thazhemadam** [comment]
The formatter suggestions are made for the formatting inconsistencies in changes introduced in the PR only, since that's the extent of scope of GitHub's comments on PRs.

**Comment by thazhemadam** [comment]
The format check failure here is not real, since the JuliaFormatter version used is å older one and the formatting is correct per the latest version. This has been fixed now and you won't be seeing these errors.

**Pull request merged**
