### PR TITLE
feat: support `SciMLBase.remake_initializeprob`

### LINKED ISSUE #2841: Remake does not respect initial conditions of unknowns determined by initialization equations
This example fails (but passes with the commented line uncommented):
```julia
using Test
using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D
using DifferentialEquations

@variables x(t)
@named sys = ODESystem([D(x) ~ 0], t; initialization_eqs = [x ~ 1.0]) # test fails with this uncommented
#@named sys = ODESystem([D(x) ~ 0], t; defaults = [x => 1.0]) # test passes with this uncommented
ssys = structural_simplify(sys)

prob1 = ODEProblem(ssys, [], (0.0, 1.0), [])
prob2 = remake(prob1, u0 = [x => 2.0])
sol2 = solve(prob2)
@test sol2[x][begin] == 2.0
```

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Close #2841 

Requires https://github.com/SciML/SciMLBase.jl/pull/731

## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by hersle** [comment]
Is this still under way?

**Comment by ChrisRackauckas** [comment]
I believe so. @AayushSabharwal we should chat about the string of unmerged PRs from last week and what it will take to get them all merged, seems like there's a few that kind of got stuck.

**Comment by AayushSabharwal** [comment]
This is waiting on the parameter initialization piece

**Comment by AayushSabharwal** [comment]
Superseded by #2928

**Pull request closed without merging**
