### PR TITLE
Fix parsing of variable names when gensym'ed in varmap_to_vars

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
what causes this case?

**Comment by asinghvi17** [comment]
I encountered it in a 2nd order ODE - essentially, the name in varmap was a gensymed name (`#DIfferentialEquations##240₊x₁`), and `varmap_to_vars` was looking for a variable name _equal_ to `x₁` (which, of course, it couldn't find).  The function would then try to index into `out` with `nothing`, which is clearly not a good idea...

**Comment by ChrisRackauckas** [comment]
I don't understand why or how it ended up getting gensym'd though. Could you give some more details on how it ended up like that? If you just do things in the REPL it's fine, so there's something extra going on here.

**Comment by asinghvi17** [comment]
The problem seems to be that `sys.x₁ === var"##ODESystem#261₊x₁"(t)`.  Consider the following (lengthy) example code:

```julia

(t, (k₁, k₂, k₃), (m₁, m₂)) = @parameters t k[1:3] m[1:2]
(x₁, x₂), = @variables x[1:2](t)
@derivatives D'~t

eqs = [
    D(D(x₁)) ~ -(k₁ * x₁ + k₂ * (x₁ - x₂))/m₁,
    D(D(x₂)) ~ -(k₃ * x₂ + k₂ * (x₂ - x₁))/m₂,
]

sys = ode_order_lowering(ODESystem(eqs, t, [x₁, x₂], [k₁, k₂, k₃, m₁, m₂]))

u0 = [
    sys.x₁ => -1.0,
    sys.x₂ =>  1.0,
    sys.x₁ˍt => 0.0,
    sys.x₂ˍt => 0.0,
]

p = [
    sys.m₁ => 1.0,
    sys.m₂ => 1.0,
    sys.k₁ => 40.0,
    sys.k₂ => 40.0,
    sys.k₃ => 40.0,
]

tspan = (0.0, 5.0)
```
Up to this point, everything works fine.  If you look at the parameter or initial condition arrays, though, you can see that the variable names are gensym'ed.

Moving on to the ODE problem construction,
```julia
prob = ODEProblem(sys, u0, tspan, p)
```
throws an `ERROR: ArgumentError: invalid index: nothing of type Nothing` in `varmap_to_vars`, because it looks for the first variable in the initial condition array, whose name is equal to the name of the variable in the system.  However, since the variables in the parameters have gensym'ed names, as you can see by a little code injection:
```julia
@eval ModelingToolkit function varmap_to_vars(varmap,varlist)
    out = similar(varmap,typeof(last(first(varmap))))
    for i in 1:length(varmap)
        ivar = convert(Variable,varmap[i][1])
        j = findfirst(x->ivar.name == convert(Variable,x).name,varlist)
        @show ivar ivar.name j varlist
        out[j] = varmap[i][2]
    end
end
```
```julia
ivar = ##ODESystem#254₊x₁
ivar.name = Symbol("##ODESystem#254₊x₁")
j = nothing
varlist = Variable[x₁ˍt, x₂ˍt, x₁, x₂]
```
the variable does seem to have a gensym'ed name, for some reason.

**Comment by ChrisRackauckas** [comment]
```julia
using ModelingToolkit

@parameters t k[1:3] m[1:2]
@variables x[1:2](t)
@derivatives D'~t

eqs = [
    D(D(x₁)) ~ -(k₁ * x₁ + k₂ * (x₁ - x₂))/m₁,
    D(D(x₂)) ~ -(k₃ * x₂ + k₂ * (x₂ - x₁))/m₂,
]

sys = ode_order_lowering(ODESystem(eqs, t, [x₁, x₂], [k₁, k₂, k₃, m₁, m₂]))

u0 = [
    x₁ => -1.0,
    x₂ =>  1.0,
    D(x₁) => 0.0,
    D(x₂) => 0.0,
]

p = [
    m₁ => 1.0,
    m₂ => 1.0,
    k₁ => 40.0,
    k₂ => 40.0,
    k₃ => 40.0,
]

tspan = (0.0, 5.0)

prob = ODEProblem(sys, u0, tspan, p)
```

works fine. I don't understand why you're namespace referencing something that isn't a component, though maybe we should be checking for the top level component name as well. However, this "fix" is in general a bad idea because it would break a lot of DSL building cases.

**Comment by asinghvi17** [comment]
Aha!  I was under the impression (not sure why) that you always had to specify the initial condition relative to the system.  Since that's not the case, I'll just close this PR.  Thanks for the help!

**Comment by ChrisRackauckas** [comment]
Yeah, the naming is for subcomponents for if you build a hierarchy of systems, but I never intended it to be used on the highest level variables. We could in the variable check to a check for the `sys.name` appended and then your setup would work, but I wouldn't necessarily say that's good style.

**Comment by hieutkt** [comment]
Sorry for hijacking this PR, I am not sure if this is the place to ask. I am having the same problem when trying to prototype a simpler model:

```
using DifferentialEquations, Plots
using ModelingToolkit

@parameters t n δ r α
@variables k(t) c(t) λ(t)
@derivatives D' ~ t


eqs = [
    D(λ) ~ -λ*(α*(k^(α-1))-(n+δ)),
    D(k) ~ k^α-c-(n+δ)*k,
    D(c) ~ λ*exp(r*t)
]

ramsey = ODESystem(eqs, t, [k, c, λ],[n, δ, r, α])

u0 = [ramsey.c => 0.4,
      ramsey.k => 1000,
      ramsey.λ => 0]

p = [ramsey.n => 0.01,
     ramsey.δ => 0.1,
     ramsey.r => 0.5,
     ramsey.α => 0.3]

tspan = (0.0,100.0)

prob = ODEProblem(ramsey,u0,tspan,p;)
```
with the following trace:

```
ERROR: ArgumentError: invalid index: nothing of type Nothing
Stacktrace:
 [1] to_index(::Nothing) at ./indices.jl:297
 [2] to_index(::Array{Float64,1}, ::Nothing) at ./indices.jl:274
 [3] to_indices at ./indices.jl:325 [inlined]
 [4] to_indices at ./indices.jl:322 [inlined]
 [5] setindex! at ./abstractarray.jl:1153 [inlined]
 [6] varmap_to_vars(::Array{Pair{Operation,Float64},1}, ::Array{Variable,1}) at /home/hieuphay/.julia/packages/ModelingToolkit/IpYP3/src/variables.jl:254
 [7] ODEProblem{true,tType,isinplace,P,F,K,PT} where PT where K where F where P where isinplace where tType(::ODESystem, ::Array{Pair{Operation,Float64},1}, ::Tuple{Float64,Float64}, ::Array{Pair{Operation,Float64},1}; version::Nothing, tgrad::Bool, jac::Bool, checkbounds::Bool, sparse::Bool, simplify::Bool, linenumbers::Bool, parallel::ModelingToolkit.SerialForm, eval_expression::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/hieuphay/.julia/packages/ModelingToolkit/IpYP3/src/systems/diffeqs/abstractodesystem.jl:260
 [8] ODEProblem{true,tType,isinplace,P,F,K,PT} where PT where K where F where P where isinplace where tType(::ODESystem, ::Array{Pair{Operation,Float64},1}, ::Tuple{Float64,Float64}, ::Array{Pair{Operation,Float64},1}) at /home/hieuphay/.julia/packages/ModelingToolkit/IpYP3/src/systems/diffeqs/abstractodesystem.jl:258
 [9] ODEProblem(::ODESystem, ::Array{Pair{Operation,Float64},1}, ::Vararg{Any,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/hieuphay/.julia/packages/ModelingToolkit/IpYP3/src/systems/diffeqs/abstractodesystem.jl:231
 [10] ODEProblem(::ODESystem, ::Array{Pair{Operation,Float64},1}, ::Vararg{Any,N} where N) at /home/hieuphay/.julia/packages/ModelingToolkit/IpYP3/src/systems/diffeqs/abstractodesystem.jl:231
 [11] top-level scope at REPL[14]:1returns
```

`findfirst` returns `Nothing`, which causes `varmap_to_vars` to throw an error.

Any help on how to solve this problem?

**Comment by ChrisRackauckas** [comment]
This should just be:

```julia
using DifferentialEquations, Plots
using ModelingToolkit

@parameters t n δ r α
@variables k(t) c(t) λ(t)
@derivatives D' ~ t


eqs = [
    D(λ) ~ -λ*(α*(k^(α-1))-(n+δ)),
    D(k) ~ k^α-c-(n+δ)*k,
    D(c) ~ λ*exp(r*t)
]

ramsey = ODESystem(eqs, t, [k, c, λ],[n, δ, r, α])

u0 = [c => 0.4,
      k => 1000,
      λ => 0]

p = [n => 0.01,
     δ => 0.1,
     r => 0.5,
     α => 0.3]

tspan = (0.0,100.0)

prob = ODEProblem(ramsey,u0,tspan,p;)
```

**Pull request closed without merging**
