### PR TITLE
Define inplace and out of place methods in ODEFunctionExpr

### PR DESCRIPTION
**Pull request by mohamed82008**
In this PR, I attempt to define an inplace and out of place methods for the ODE function in `ODEFunctionExpr`. I did this on GitHub for some reason so I didn't run local tests yet. Will add a test after I open the PR.

### CODE REVIEW

**Comment by mohamed82008** [comment]
This is ready for review.

**Comment by ChrisRackauckas** [comment]
Can this get a test in https://github.com/SciML/ModelingToolkit.jl/blob/master/test/odesystem.jl to check at least that `f` works with both calls after this is evaled?

**Comment by mohamed82008** [comment]
Tests added.

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
Looks like a real test failure.

**Comment by mohamed82008** [comment]
>Looks like a real test failure.

Ya the loop masked some variables used outside.

**Pull request merged**
