### PR TITLE
Add tests for Jumps created through reactions.

### PR DESCRIPTION
**Pull request by TorkelE**
Here comes another set of tests to ensure that jumps created through reactions are working.

There is one error, on line `126`, for `i = 16`:
```julia
crj = MT.assemble_crj(js, js.eqs[i], statetoid)
```
generates a
```error
MethodError: no method matching (::JuliaVariables.var"#IS_SCOPED#64"{IdDict{Expr,Any}})(::JuliaVariables.State, ::JuliaVariables.SymRef)
Closest candidates are:
  IS_SCOPED(::JuliaVariables.State, !Matched::Expr) at /home/torkelloman/.julia/packages/JuliaVariables/PPPMs/src/JuliaVariables.jl:234
in top-level scope at reactionsystem.jl:141
in assemble_crj at dev/ModelingToolkit/src/systems/jumps/jumpsystem.jl:38
in generate_rate_function at dev/ModelingToolkit/src/systems/jumps/jumpsystem.jl:19 
in build_function##kw at dev/ModelingToolkit/src/build_function.jl:61 
in #build_function#184 at dev/ModelingToolkit/src/build_function.jl:61
in  at dev/ModelingToolkit/src/build_function.jl:109
in #_build_function#187 at dev/ModelingToolkit/src/build_function.jl:130
in mk_function at GeneralizedGenerated/YYD7s/src/GeneralizedGenerated.jl:22
in solve at JuliaVariables/PPPMs/src/JuliaVariables.jl:133
in #solve#44 at JuliaVariables/PPPMs/src/JuliaVariables.jl:504
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:498
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:375
in ##JuliaVariables 181#441#118 at base/none 
in ##JuliaVariables 183#443#119 at JuliaVariables/PPPMs/src/JuliaVariables.jl:432 
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:226
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:206
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:226
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:159
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:436
in ##JuliaVariables 171#431#147 at base/none 
in ##JuliaVariables 173#433#148 at JuliaVariables/PPPMs/src/JuliaVariables.jl:439 
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:436
in ##JuliaVariables 171#431#147 at base/none 
in ##JuliaVariables 173#433#148 at JuliaVariables/PPPMs/src/JuliaVariables.jl:439 
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:356
in ##JuliaVariables 202#462#112 at base/none 
in ##JuliaVariables 204#464#113 at JuliaVariables/PPPMs/src/JuliaVariables.jl:357 
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:196
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:360
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:170
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:277
in ##JuliaVariables 310#570#78 at base/none 
in ##JuliaVariables 312#572#79 at JuliaVariables/PPPMs/src/JuliaVariables.jl:280 
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:159
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:436
in ##JuliaVariables 171#431#147 at base/none 
in ##JuliaVariables 173#433#148 at JuliaVariables/PPPMs/src/JuliaVariables.jl:439 
in  at JuliaVariables/PPPMs/src/JuliaVariables.jl:246
in ##JuliaVariables 359#619#66 at base/none 
in ##JuliaVariables 361#621#67 at base/none 
in ##JuliaVariables 367#627#68 at base/none 
in ##JuliaVariables 369#629#69 at JuliaVariables/PPPMs/src/JuliaVariables.jl:253 
```
The corresponding reaction is:
```julia
Reaction(k[16], [A], [B]; only_use_rate=true),             # A -> B with custom rate.
```
and the jump
```julia
jumps[16] = ConstantRateJump((u,p,t) -> p[16], integrator -> (integrator.u[1] -= 1; integrator.u[2] += 1;))
```

I believe that the problem is when you try to make a `ConstantRateJump` with only a constant (here `k[16]`) as the actual rate. This using `assemble_crj()`. @isaacsas Do you know what is going on? Should we skip the test, or is there something fishy going on in `assemble_crj()`?

### CODE REVIEW

**Comment by isaacsas** [comment]
I’ll take a look later tonight and let you know.

**Comment by isaacsas** [comment]
@ChrisRackauckas Could this be a GeneralizedGenerated issue? It seems to crash in `build_function` when building the rate function, but if I have `build_function` instead return the expression and use `eval` it seems to compile fine.

**Comment by isaacsas** [comment]
Here's a simpler example:
```julia
using ModelingToolkit
MT = ModelingToolkit

@parameters t k
@variables A(t) B(t)

rx = ConstantRateJump(k, [A ~ A - 1, B ~ B + 1])
js = JumpSystem([rx], t, [A,B], [k])
statetoid = Dict(convert(Variable,state) => i for (i,state) in enumerate(states(js)))
MT.assemble_crj(js, rx, statetoid)
```

**Comment by ChrisRackauckas** [comment]
Yeah that sounds like a GG issue.

**Comment by isaacsas** [comment]
A bit better for seeing what is going on:
```julia
using ModelingToolkit, MacroTools
MT = ModelingToolkit

@parameters t k
@variables A(t) B(t)

rx = ConstantRateJump(k, [A ~ A - 1, B ~ B + 1])
js = JumpSystem([rx], t, [A,B], [k])
statetoid = Dict(convert(Variable,state) => i for (i,state) in enumerate(states(js)))

# expression for rate function:
ex = MacroTools.striplines(build_function(rx.rate, states(js), parameters(js),independent_variable(js),expression=Val{true}))
f = eval(ex)
f([10,5], [11.0], 1.0)

# MT.assemble_crj(js, rx, statetoid) calls the following which crashes
g = build_function(rx.rate, states(js), parameters(js),independent_variable(js),expression=Val{false})
```

**Comment by ChrisRackauckas** [comment]
Can you isolate that expression to an MWE?

**Comment by isaacsas** [comment]
@torkel I'd just comment out for now. This is a pretty weird case since normally we'd use a MassActionJump for a zero order reaction. But it does mean someone coding up a zero order reaction as a ConstantRateJump manually is going to get a crash for some reason.

**Comment by isaacsas** [comment]
The generated expression is:
```julia
:((var"##MTKArg#378", var"##MTKArg#379", var"##MTKArg#380")->begin
          @inbounds begin
                  let (A, B, k, t) = (var"##MTKArg#378"[1], var"##MTKArg#378"[2], var"##MTKArg#379"[1], var"##MTKArg#380")
                      k
                  end
              end
      end)
```

**Comment by ChrisRackauckas** [comment]
Can you recreate it purely with GG? `runtime_eval(ex)(u,p,t)`?

**Comment by isaacsas** [comment]
The expression above gives the same error with `runtime_eval`. Changing `k` to `2*k` seems to get rid of it.

**Comment by ChrisRackauckas** [comment]
Open an issue with GG. That's a weird edge case.

**Comment by isaacsas** [comment]
Strangely this works fine
```julia
ex3 = :((u, p, t)->begin
          @inbounds begin
                  let (A, B, k, t) = (u[1], u[2], p[1], t)
                      k
                  end
              end
      end)
```

**Comment by isaacsas** [comment]
There's something more going on. Simply pasting the expression that doesn't work above in a clear REPL and using with `runtime_eval` works fine.

**Comment by ChrisRackauckas** [comment]
Open an issue to track the upstream issue.

**Comment by isaacsas** [comment]
Yup, already did that: https://github.com/SciML/ModelingToolkit.jl/issues/359

**Pull request merged**
