### PR TITLE
add isautonomous

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Checks for whether the ODESystem is autonomous

@shashi is there a better way to do this?

### CODE REVIEW

**Review by YingboMa — APPROVED** [review]
LGTM

**Comment by shashi** [comment]
You can use `jacobian_sparsity` for speed.

**Comment by YingboMa** [comment]
`jacobian_sparsity` will think that `x(t)` is time dependent.

**Comment by ChrisRackauckas** [comment]
Yeah. But the method of jacobian_sparsity could be used w.r.t. `t` and that would speed it up.

**Comment by ChrisRackauckas** [comment]
Opened an issue in https://github.com/SciML/ModelingToolkit.jl/issues/816 . The issue is that sparsity w.r.t. `t` still has `D(x(t))` as non-zero, so we'd then have to zero all of those, and then use the sparsity. So it's not trivial enough to do right now, but it's something we could think about for the future.

**Pull request merged**
