### PR TITLE
Backport #2719 to MTK v8

### PR DESCRIPTION
**Pull request by devmotion**
The PR backports #2719 to a MTK v8 on a new `backport_8` branch. I can't use MTK v9 yet due to the incompatibility with Catalyst, so #2719 is not sufficient for my project.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Format so tests run

**Comment by devmotion** [comment]
I reformatted the code (which blows up the diff). It seems only a subset of CI is run on PRs that do not target the master branch - one problem with the existing version bounds for MTK v8 are the breaking changes in SymbolicUtils 1.6.0 (see e.g. https://github.com/SciML/ModelingToolkit.jl/actions/runs/9150353436/job/25155026031#step:6:1243) and the ADTypes changes (and some incorrect version bounds in NonlinearSolve it seems: https://github.com/SciML/ModelingToolkit.jl/actions/runs/9150353436/job/25155025675?pr=2726#step:6:1903). In my package that's not too problematic since I pin these packages anyway but generally that's annoying for users.

**Comment by ChrisRackauckas** [comment]
@thazhemadam do you know how to make this run?

**Comment by ChrisRackauckas** [comment]
Can we just bound SymbolicUtils?

**Comment by ChrisRackauckas** [comment]
Limit SymbolicIndexingInterface as well?

**Comment by devmotion** [comment]
Why?

**Comment by gdalle** [comment]
I think the problem here is the same as https://github.com/SciML/SciMLBase.jl/pull/689#issuecomment-2124463847

It's not an ADTypes bug per se, it's just that an environment with ADTypes v1 installed leaks into an environment where only ADTypes v0.2 should be allowed, due to Pkg manipulations during testing. With fresh environments this probably wouldn't happen

**Comment by Vaibhavdixit02** [comment]
Yeah we can do that, I am not sure how it can be changed in the registry though. Can it just be bounded to v1.0.1 here?

**Comment by gdalle** [comment]
One option is to yank those versions, aka get rid of them completely. That's what I did in https://github.com/JuliaRegistries/General/pull/107391

https://github.com/JuliaRegistries/General?tab=readme-ov-file#when-is-yanking-a-release-appropriate

**Comment by gdalle** [comment]
Let's discuss on the General PR https://github.com/JuliaRegistries/General/pull/107391

**Comment by devmotion** [comment]
@gdalle Tests still fail due to ADTypes it seems.

**Comment by gdalle** [comment]
It's installing OptimizationBase v0.0.7, which I thought I had yanked?

**Comment by ChrisRackauckas** [comment]
The package servers can take awhile to get the updated registries.

**Comment by ChrisRackauckas** [comment]
r

**Pull request merged**
