### PR TITLE
Improve BifurcationKit extension

### PR DESCRIPTION
**Pull request by TorkelE**
Changes:
- If the MTK system has default values for e.g. parameters, this is now properly handled.
- If the MTK system has observables (e.g. due to structural simplify, or because it has been generated by certain Catalyst systems), these can now be selected as the plotting variables of the diagram.
- Much improved test cases.

E.g. this should now work:
```julia
using BifurcationKit, ModelingToolkit
# Creates model, and uses `structural_simplify` to generate observables.
@parameters μ p=2
@variables t x(t) y(t) z(t)
D = Differential(t)
eqs = [0 ~ μ - x^3 + 2x^2,
       0 ~ p*μ - y,
       0 ~ y - z]    
@named nsys = NonlinearSystem(eqs, [x, y, z], [μ, p])
nsys = structural_simplify(nsys)

# Creates BifurcationProblem.
bif_par = μ
p_start = [μ => 1.0]
u0_guess = [x => 1.0, y => 0.1, z => 0.1]
plot_var = x;
bprob = BifurcationProblem(nsys, u0_guess, p_start, bif_par; plot_var=plot_var)

# Computes bifurcation diagram.
p_span = (-4.3, 12.0)
opt_newton = NewtonPar(tol = 1e-9, max_iterations = 20)
opts_br = ContinuationPar(dsmin = 0.001, dsmax = 0.05, ds = 0.01,
    max_steps = 100, nev = 2, newton_options = opt_newton,
    p_min = p_span[1], p_max = p_span[2],
    detect_bifurcation = 3, n_inversion = 4, tol_bisection_eigenvalue = 1e-8, dsmin_bisection = 1e-9);   
bif_dia = bifurcationdiagram(bprob, PALC(), 2, (args...) -> opts_br; bothside=true)
plot(bif_dia)
```

### CODE REVIEW

**Comment by TorkelE** [comment]
The formatter updated a lot of other files as well, right now I only pushed those affecting files this PR adds.
(but could push the rest, if that is desired)

**Comment by isaacsas** [comment]
Don’t run format. It is still broken.

**Comment by YingboMa** [comment]
It seems like you need to update local JuliaFormatter.

And yeah, I am very committed to not merging any PR that doesn't pass format-check.

**Comment by TorkelE** [comment]
No, I agree fully. Given the formatter is in place and used, it should be run fully for every PR. Had Catalyst used in currently I would have been the same there.

I have updated the formatted and rerun it, hopefully it should work now.

**Review by YingboMa — APPROVED** [review]

**Pull request merged**
