### PR TITLE
Add observed function for `NonlinearFunction`s

### PR DESCRIPTION
**Pull request by YingboMa**
Need https://github.com/SciML/SciMLBase.jl/pull/39

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
It would be good to handle SteadyStateProblem too.

**Comment by YingboMa** [comment]
Should handling `SteadyStateProblem` be in SciML? `SteadyStateProblem` uses `ODEFunction`, right?

**Comment by ChrisRackauckas** [comment]
>Should handling SteadyStateProblem be in SciML? SteadyStateProblem uses ODEFunction, right?

It uses ODEFunction, where it's assumed that `t = Inf`.

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by pepijndevos** [comment]
It seems the SciMLBase PR has been merged, so is this good to go now?

**Comment by ChrisRackauckas** [comment]
Retriggered the tests and they seem to hit a real CI failure.

**Pull request merged**
