### PR TITLE
feat: improve error message when system contains array equations

### LINKED ISSUE #2597: Symbolic-array system bug in counting equations and variables
MWE
```julia
@mtkmodel Foo begin
    @variables begin
        x(t)[1:2]
    end
    @equations begin
        D.(x) ~ .-x
    end
end
@named foo = Foo()
foo = complete(foo)
prob = ODEProblem(foo, Dict(foo.x => [1.0, 1]), (0.0, 1.0))
sol = solve(prob, Rodas4())
```
```
julia> prob = ODEProblem(foo, Dict(foo.x => [1.0, 1]), (0.0, 1.0))
ERROR: ArgumentError: Equations (1), unknowns (2), and initial conditions (2) are of different lengths. To allow a different number of equations than unknowns use kwarg check_length=false.
```

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Close #2597 

## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Why would this be required? The codegen doesn't require it if it's a true ODE.

**Comment by AayushSabharwal** [comment]
It doesn't really work very reliably.

```julia
@variables x(t)[1:2]
@named sys = ODESystem(D(x) ~ x, t)
sys = complete(sys)
prob = ODEProblem(sys, ...)
```
This errors in `calculate_massmatrix` because that can't handle array equations and needs them scalarized

```julia
@named sys = ODESystem(D(x) ~ x, t, [x...], [])
```

If I comment out `check_eqs_u0` this errors in `generate_function` because `check_lhs` finds that the variable inside the derivative `D(x)` isn't in the list of unknowns.

I _could_ make these cases work, but all of the fixes boil down to scalarizing the equations and/or unknowns.

**Comment by AayushSabharwal** [comment]
And if there are multiple array unknowns or a mix of array/scalars then codegen also won't work

**Comment by ChrisRackauckas** [comment]
`calculate_massmatrix` needs to semantically scalarize and show it's constant. 

> And if there are multiple array unknowns or a mix of array/scalars then codegen also won't work without scalarizing the equations.

Is that really the case? Symbolics.jl handled this awhile back.

**Comment by ChrisRackauckas** [comment]
I see no issue with a temporary error message that told people as a temporary workaround this is required, though I think we should look at some of the codegen here since Symbolics should already handle these cases.

**Comment by AayushSabharwal** [comment]
The problem with the codegen is that this system:
```julia
julia> @named sys = ODESystem([D(x) ~ x, D(y) ~ t], t, [x..., y])
```
Generates this code:
```julia
RuntimeGeneratedFunction(#=in ModelingToolkit=#, #=using ModelingToolkit=#, :((ˍ₋out, ˍ₋arg1, t)->begin
          #= /Users/aayush/.julia/packages/SymbolicUtils/ij6YM/src/code.jl:385 =#
          #= /Users/aayush/.julia/packages/SymbolicUtils/ij6YM/src/code.jl:386 =#
          #= /Users/aayush/.julia/packages/SymbolicUtils/ij6YM/src/code.jl:387 =#
          begin
              begin
                  var"x(t)" = view(ˍ₋arg1, 1:2)
                  begin
                      begin
                          #= /Users/aayush/.julia/packages/Symbolics/XnDVB/src/build_function.jl:546 =#
                          #= /Users/aayush/.julia/packages/SymbolicUtils/ij6YM/src/code.jl:434 =# @inbounds begin
                                  #= /Users/aayush/.julia/packages/SymbolicUtils/ij6YM/src/code.jl:430 =#
                                  ˍ₋out[1] = var"x(t)"
                                  ˍ₋out[2] = t
                                  #= /Users/aayush/.julia/packages/SymbolicUtils/ij6YM/src/code.jl:432 =#
                                  nothing
                              end
                      end
                  end
              end
          end
      end))
```

Which again points to the fact that the system needs to be scalarized

**Comment by AayushSabharwal** [comment]
Also without `structural_simplify` it's up to the user to ensure the equations and unknowns are in the correct order.

**Comment by ChrisRackauckas** [comment]
Okay we should fix that, it's fixable. For now, mention that a temporary workaround is to scalarize or structural simplify.

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
@AayushSabharwal some test greening https://github.com/SciML/ModelingToolkit.jl/actions/runs/11185499006/job/31098502328#step:6:2267 ?

**Pull request merged**
