### PR TITLE
Distributed parallelism build targets

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
```julia 
using ModelingToolkit, OrdinaryDiffEq

@parameters t σ ρ β
@variables x(t) y(t) z(t)
@derivatives D'~t

eqs = [D(x) ~ σ*(y-x),
       D(y) ~ x*(ρ-z)-y,
       D(z) ~ x*y - β*z]

lorenz1 = ODESystem(eqs,name=:lorenz1)
lorenz2 = ODESystem(eqs,name=:lorenz2)

@variables a
@parameters γ
connections = [0 ~ lorenz1.x + lorenz2.y + a*γ]
connected = ODESystem(connections,t,[a],[γ],systems=[lorenz1,lorenz2])

using Distributed
addprocs(2)
generate_function(connected,parallel=ModelingToolkit.DistributedForm())[2]
generate_jacobian(connected,parallel=ModelingToolkit.DistributedForm(),sparse=true)[2]
```

gives:

```julia
:((var"##MTIIPVar#365", var"##MTKArg#361", var"##MTKArg#362", var"##MTKArg#363")->begin
          @inbounds begin
                  let (a, lorenz1₊x, lorenz1₊y, lorenz1₊z, lorenz2₊x, lorenz2₊y, lorenz2₊z, γ, lorenz1₊ρ, lorenz1₊σ, lorenz1₊β, lorenz2₊ρ, lorenz2₊σ, lorenz2₊β, t) = (var"##MTKArg#361"[1], var"##MTKArg#361"[2], var"##MTKArg#361"[3], var"##MTKArg#361"[4], var"##MTKArg#361"[5], var"##MTKArg#361"[6], var"##MTKArg#361"[7], var"##MTKArg#362"[1], var"##MTKArg#362"[2], var"##MTKArg#362"[3], var"##MTKArg#362"[4], var"##MTKArg#362"[5], var"##MTKArg#362"[6], var"##MTKArg#362"[7], var"##MTKArg#363")
                      begin
                          begin
                              var"##MTSpawnVar#368" = Distributed.@spawnat(2, begin
                                          [(lorenz1₊x + lorenz2₊y) + a * γ, lorenz1₊σ * (lorenz1₊y - lorenz1₊x), lorenz1₊x * (lorenz1₊ρ - lorenz1₊z) - lorenz1₊y, lorenz1₊x * lorenz1₊y - lorenz1₊β * lorenz1₊z]
                                      end)
                          end
                          begin
                              var"##MTSpawnVar#369" = Distributed.@spawnat(3, begin
                                          [lorenz2₊σ * (lorenz2₊y - lorenz2₊x), lorenz2₊x * (lorenz2₊ρ - lorenz2₊z) - lorenz2₊y, lorenz2₊x * lorenz2₊y - lorenz2₊β * lorenz2₊z]
                                      end)
                          end
                      end
                      var"##MTReduceVar#366" = fetch(var"##MTSpawnVar#368")
                      var"##MTReduceVar#367" = fetch(var"##MTSpawnVar#369")
                      begin
                          var"##MTIIPVar#365"[1] = getindex(var"##MTReduceVar#366", 1)
                          var"##MTIIPVar#365"[2] = getindex(var"##MTReduceVar#366", 2)
                          var"##MTIIPVar#365"[3] = getindex(var"##MTReduceVar#366", 3)
                          var"##MTIIPVar#365"[4] = getindex(var"##MTReduceVar#366", 4)
                          var"##MTIIPVar#365"[5] = getindex(var"##MTReduceVar#367", 1)
                          var"##MTIIPVar#365"[6] = getindex(var"##MTReduceVar#367", 2)
                          var"##MTIIPVar#365"[7] = getindex(var"##MTReduceVar#367", 3)
                      end
                  end
              end
          nothing
      end)
```

and

```julia
:((var"##MTIIPVar#371", var"##MTKArg#367", var"##MTKArg#368", var"##MTKArg#369")->begin
          @inbounds begin
                  let (a, lorenz1₊x, lorenz1₊y, lorenz1₊z, lorenz2₊x, lorenz2₊y, lorenz2₊z, γ, lorenz1₊σ, lorenz1₊β, lorenz1₊ρ, lorenz2₊σ, lorenz2₊β, lorenz2₊ρ, t) = (var"##MTKArg#367"[1], var"##MTKArg#367"[2], var"##MTKArg#367"[3], var"##MTKArg#367"[4], var"##MTKArg#367"[5], var"##MTKArg#367"[6], var"##MTKArg#367"[7], var"##MTKArg#368"[1], var"##MTKArg#368"[2], var"##MTKArg#368"[3], var"##MTKArg#368"[4], var"##MTKArg#368"[5], var"##MTKArg#368"[6], var"##MTKArg#368"[7], var"##MTKArg#369")
                      begin
                          begin
                              var"##MTSpawnVar#374" = Distributed.@spawnat(2, begin
                                          [1, -1lorenz1₊σ, -1lorenz1₊z + lorenz1₊ρ, lorenz1₊y, lorenz1₊σ, -1, lorenz1₊x, -1lorenz1₊x, -1lorenz1₊β]
                                      end)
                          end
                          begin
                              var"##MTSpawnVar#375" = Distributed.@spawnat(3, begin
                                          [-1lorenz2₊σ, -1lorenz2₊z + lorenz2₊ρ, lorenz2₊y, 1, lorenz2₊σ, -1, lorenz2₊x, -1lorenz2₊x, -1lorenz2₊β]
                                      end)
                          end
                      end
                      var"##MTReduceVar#372" = fetch(var"##MTSpawnVar#374")
                      var"##MTReduceVar#373" = fetch(var"##MTSpawnVar#375")
                      begin
                          (var"##MTIIPVar#371").nzval[1] = getindex(var"##MTReduceVar#372", 1)
                          (var"##MTIIPVar#371").nzval[2] = getindex(var"##MTReduceVar#372", 2)
                          (var"##MTIIPVar#371").nzval[3] = getindex(var"##MTReduceVar#372", 3)
                          (var"##MTIIPVar#371").nzval[4] = getindex(var"##MTReduceVar#372", 4)
                          (var"##MTIIPVar#371").nzval[5] = getindex(var"##MTReduceVar#372", 5)
                          (var"##MTIIPVar#371").nzval[6] = getindex(var"##MTReduceVar#372", 6)
                          (var"##MTIIPVar#371").nzval[7] = getindex(var"##MTReduceVar#372", 7)
                          (var"##MTIIPVar#371").nzval[8] = getindex(var"##MTReduceVar#372", 8)
                          (var"##MTIIPVar#371").nzval[9] = getindex(var"##MTReduceVar#372", 9)
                          (var"##MTIIPVar#371").nzval[10] = getindex(var"##MTReduceVar#373", 1)
                          (var"##MTIIPVar#371").nzval[11] = getindex(var"##MTReduceVar#373", 2)
                          (var"##MTIIPVar#371").nzval[12] = getindex(var"##MTReduceVar#373", 3)
                          (var"##MTIIPVar#371").nzval[13] = getindex(var"##MTReduceVar#373", 4)
                          (var"##MTIIPVar#371").nzval[14] = getindex(var"##MTReduceVar#373", 5)
                          (var"##MTIIPVar#371").nzval[15] = getindex(var"##MTReduceVar#373", 6)
                          (var"##MTIIPVar#371").nzval[16] = getindex(var"##MTReduceVar#373", 7)
                          (var"##MTIIPVar#371").nzval[17] = getindex(var"##MTReduceVar#373", 8)
                          (var"##MTIIPVar#371").nzval[18] = getindex(var"##MTReduceVar#373", 9)
                      end
                  end
              end
          nothing
      end)
```

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@vchuravy @shashi let me know if there's a slightly better function form I should be targeting.

@jpsamaroo this is the static scheduler version where we just split it up into equal parts. The next step will be a Dagger version that is smarter based on some estimated cost, splitting it up so that way the data sends are smaller.

I only expect this to make sense for very large equations.

**Comment by vchuravy** [comment]
I think the only thing that would be better is to avoid the cost of constructing the closure and to use `Distributed.remotecall((args...)->(#==#), p, args...)`. So that the closure can be reused.

**Comment by ChrisRackauckas** [comment]
How would that reuse the same closure if it's sending over the numbers?

**Comment by ChrisRackauckas** [comment]
Demonstrating automatic distributed parallelism of Julia code, complete with a >10x slowdown!

```julia
using ModelingToolkit, LinearAlgebra, SparseArrays

# Define the constants for the PDE
const α₂ = 1.0
const α₃ = 1.0
const β₁ = 1.0
const β₂ = 1.0
const β₃ = 1.0
const r₁ = 1.0
const r₂ = 1.0
const _DD = 100.0
const γ₁ = 0.1
const γ₂ = 0.1
const γ₃ = 0.1
const N = 8
const X = reshape([i for i in 1:N for j in 1:N],N,N)
const Y = reshape([j for i in 1:N for j in 1:N],N,N)
const α₁ = 1.0.*(X.>=4*N/5)

const Mx = Tridiagonal([1.0 for i in 1:N-1],[-2.0 for i in 1:N],[1.0 for i in 1:N-1])
const My = copy(Mx)
Mx[2,1] = 2.0
Mx[end-1,end] = 2.0
My[1,2] = 2.0
My[end,end-1] = 2.0

# Define the initial condition as normal arrays
@variables du[1:N,1:N,1:3] u[1:N,1:N,1:3] MyA[1:N,1:N] AMx[1:N,1:N] DA[1:N,1:N]

# Define the discretized PDE as an ODE function
function f(du,u,p,t)
   A = @view  u[:,:,1]
   B = @view  u[:,:,2]
   C = @view  u[:,:,3]
  dA = @view du[:,:,1]
  dB = @view du[:,:,2]
  dC = @view du[:,:,3]
  mul!(MyA,My,A)
  mul!(AMx,A,Mx)
  @. DA = _DD*(MyA + AMx)
  @. dA = DA + α₁ - β₁*A - r₁*A*B + r₂*C
  @. dB = α₂ - β₂*B - r₁*A*B + r₂*C
  @. dC = α₃ - β₃*C + r₁*A*B - r₂*C
end

f(du,u,nothing,0.0)

multithreadedf = eval(ModelingToolkit.build_function(du,u,parallel=ModelingToolkit.MultithreadedForm())[2])
_du = rand(N,N,3)
_u = rand(N,N,3)
multithreadedf(_du,_u)

using Distributed
addprocs(4)
distributedf = eval(ModelingToolkit.build_function(du,u,parallel=ModelingToolkit.DistributedForm())[2])

MyA = zeros(N,N)
AMx = zeros(N,N)
DA  = zeros(N,N)
using BenchmarkTools
@btime f(_du,_u,nothing,0.0)
@btime multithreadedf(_du,_u)
@btime distributedf(_du,_u)
```

```julia
4.043 μs (26 allocations: 848 bytes)
1.390 μs (22 allocations: 7.94 KiB)
8.440 ms (1869 allocations: 52.73 KiB)
```

**Comment by ChrisRackauckas** [comment]
Then the sparse Jacobian computation:

```julia
jac = sparse(ModelingToolkit.jacobian(vec(du),vec(u),simplify=false))
serialjac = eval(ModelingToolkit.build_function(vec(jac),u)[2])
multithreadedjac = eval(ModelingToolkit.build_function(vec(jac),u,parallel=ModelingToolkit.MultithreadedForm())[2])
distributedjac = eval(ModelingToolkit.build_function(vec(jac),u,parallel=ModelingToolkit.DistributedForm())[2])

_jac = similar(jac,Float64)
@btime serialjac(_jac,_u)
@btime multithreadedjac(_jac,_u)
@btime distributedjac(_jac,_u)
```

@shashi the simplify is too slow to be on here (didn't let it finish), but it needs to be on in order to get performance on the compilation of the multithreaded form. So this might be a good test case for simplify performance.

**Pull request merged**
