### PR TITLE
Default to using fully_determined when possible in initialization

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
This should give better error messages

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I'm not sure this is legal in general. Counting the number of equations does not actually give if fully determined since there might be trivial equations, and the tests suggest that's not too uncommon for initializations? @YingboMa opinion?

**Comment by AayushSabharwal** [comment]
What if we make it so that passing `fully_determined = missing` will `try-catch` the consistency check and take the appropriate code path?

**Review by YingboMa — COMMENTED** [review]
This is not correct in general. You should check if the DAE system has finite index.

**Comment by ChrisRackauckas** [comment]
The DAE system would have to already be structurally simplified at this point, so it should be index 1 or have errored already?

**Pull request closed without merging**
