### PR TITLE
leave D(foo(t)) untouched if foo is not a known function

### PR DESCRIPTION
**Pull request by shashi**
cc @YingboMa

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by YingboMa** [comment]
`derivative` or `derivative_idx` probably should not be a user API, since it doesn't apply the chain rule. But the name makes it super confusing, as there are `gradient` and `jacobian`, and they are meant to be used by the users.

**Comment by YingboMa** [comment]
Can we define `ModelingToolkit.derivative(f, x) = expand_derivatives(Differential(x)(f))`?

**Comment by ChrisRackauckas** [comment]
>Can we define ModelingToolkit.derivative(f, x) = expand_derivatives(Differential(x)(f))?

Yes, we should.

**Comment by shashi** [comment]
> Can we define ModelingToolkit.derivative(f, x) = expand_derivatives(Differential(x)(f))?

Of course we can, but in that case I'd like to rename the `derivative` function which is meant to be extended to define differentiation on new functions.

deprecating that should be possible?

**Comment by YingboMa** [comment]
It seem hard to deprecate. `derivative` was a public API before and was in the documentation. It's just that the definition doesn't make sense as it doesn't use chain rules.

**Pull request merged**
