### PR TITLE
get state dependencies, observed -> SymbolicIndexingInterface

### PR DESCRIPTION
**Pull request by xtalax**
Merge order is:
1. https://github.com/SciML/SymbolicIndexingInterface.jl/pull/7
2. https://github.com/SciML/SciMLBase.jl/pull/392 
3. https://github.com/SciML/OrdinaryDiffEq.jl/pull/1867
4. https://github.com/SciML/ModelingToolkit.jl/pull/2071 (this)

### CODE REVIEW

**Review by YingboMa — COMMENTED** [review]
This still needs tests.

**Comment by xtalax** [comment]
Yes it does, just wanted to draw attention to it

**Comment by xtalax** [comment]
The tests relevant to this are passing with all PRs dev'd, but there is an error in Linearization tests consistent with some `Num`s ending up embedded in a generated expression, don't know where this is coming from

**Comment by xtalax** [comment]
passing locally

**Comment by ChrisRackauckas** [comment]
Handled separately.

**Pull request closed without merging**
