### PR TITLE
added test for symbolic continuous_events

### PR DESCRIPTION
**Pull request by hstrey**

### CODE REVIEW

**Review by YingboMa — CHANGES_REQUESTED** [review]
Format

**Comment by YingboMa** [comment]
Checkout https://github.com/SciML/ModelingToolkit.jl/blob/master/CONTRIBUTING.md

**Comment by isaacsas** [comment]
It might make more sense to rename the `root_equations.jl` test file to `symbolic_events.jl` and then throw this new test in a let block at the end. That file has a ton of tests for events already.

**Comment by isaacsas** [comment]
You need to update `runtests.jl` too to call the new file name.

**Comment by hstrey** [comment]
symbolic_events.jl was already in runtests.jl

**Comment by hstrey** [comment]
My new tests passed.  I am not sure about the fail of coverage/coveralls, but from my end, this is ready to merge.  This was my first pull request for an open-source project.  Thanks

**Comment by isaacsas** [comment]
Thanks for the test!

**Comment by baggepinnen** [comment]
> his was my first pull request for an open-source project. 

@hstrey be careful, this can be addictive ;) 

Thanks for the tests!

**Pull request merged**
