### PR TITLE
feat: add symbolic tstops support to `ODESystem`

### PR DESCRIPTION
**Pull request by AayushSabharwal**
## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by isaacsas** [comment]
This is really nice. Is there any reason not to add to SDE and jump systems too?

**Comment by AayushSabharwal** [comment]
I'm yet to add the solver infrastructure there

**Comment by ChrisRackauckas** [comment]
What's up with the homotopy continuation tests? That's clearly not related though, but should get a follow up.

**Comment by AayushSabharwal** [comment]
> What's up with the homotopy continuation tests? That's clearly not related though, but should get a follow up.

Weird that the only failure is on LTS. I'll investigate.

**Pull request merged**
