### PR TITLE
fix!: require explicit independent variable for ODESystem

### PR DESCRIPTION
**Pull request by AayushSabharwal**
## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by oscardssmith** [comment]
What does this fix? This seems like a really breaking change without a ton of benefit.

**Comment by ChrisRackauckas** [comment]
It fixes a lot since the equation parsing had a few edge cases where it's not generally fixable without requiring that the independent variable is known.

**Comment by ChrisRackauckas** [comment]
If you dig through the closed issues you'll find many cases where ODESystem did it's decomposition incorrectly and that led to an error, with the fix being to use the "right" constructor, i.e. pass in the independent variable too. Some of those cases simply have too little information to solve so the heuristic for determining what is the independent variable is just not generally solvable. Given it's not generally solvable, the best thing to do is to just ask users for it. It's easy and it fixes all of those potential issues.

**Comment by ChrisRackauckas** [comment]
Does @mtkbuild need a change?

**Pull request merged**
