### PR TITLE
SDEProblem from SDESystem fix

### PR DESCRIPTION
**Pull request by isaacsas**
Seemed to be a typo in `SDEProblem` construction.

### CODE REVIEW

**Comment by isaacsas** [comment]
@ChrisRackauckas  Would it make sense to also add:
```julia
function DiffEqBase.SDEProblem(sys::AbstractODESystem, args...; kwargs...)
    SDEProblem{true}(sys, args...; kwargs...)
end
```
similar to what you have for `ODEProblem`s?

**Comment by isaacsas** [comment]
Sorry, I mean
```julia
function DiffEqBase.SDEProblem(sys::AbstractSDESystem, args...; kwargs...)
    SDEProblem{true}(sys, args...; kwargs...)
end
```

**Comment by ChrisRackauckas** [comment]
Oh yes, that would make sense.

**Comment by isaacsas** [comment]
Will submit shortly

**Pull request merged**
