### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by isaacsas**
Changes system field access to getters to remove some warnings in tests, and removes a dangling `@show`.

### CODE REVIEW

**Comment by isaacsas** [comment]
It seems like the repo hadn't been formatted on a previous merge, so I've formatted too.

**Comment by isaacsas** [comment]
Seems like there are some issues in MTK tests at the moment.

**Comment by ChrisRackauckas** [comment]
> It seems like the repo hadn't been formatted on a previous merge, so I've formatted too.

I thought we were still waiting on formatter updates?

**Comment by ChrisRackauckas** [comment]
@AayushSabharwal this looks SII related? https://github.com/SciML/ModelingToolkit.jl/actions/runs/7367005795/job/20049779084?pr=2405#step:6:765

**Comment by ChrisRackauckas** [comment]
Errors unrelated. Let's get to that test error.

**Comment by isaacsas** [comment]
> > It seems like the repo hadn't been formatted on a previous merge, so I've formatted too.
> 
> I thought we were still waiting on formatter updates?

I thought @YingboMa was still requiring the formatter for merging here so I wanted to respect that. I’ve been waiting on it being updated for Catalyst and JumpProcesses.

**Pull request merged**
