### PR TITLE
Add MethodOfLines to Downstream

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@xtalax what is this failure?

**Comment by xtalax** [comment]
Haven't seen this before, this passed on the previous CI run. I will investigate, looks like time independent being used to index a time dependant solution

**Comment by xtalax** [comment]
as of MTK v8.29.1 this error is not present
...
And I do not reproduce as of 8.30, something in its dependencies is limiting MTK to this version

**Comment by xtalax** [comment]
@ChrisRackauckas please cycle this and I will fix what comes up

**Comment by xtalax** [comment]
please also add the burgers group as this fails due to a regression from upstream

**Pull request merged**
