### PR TITLE
upper bound Symbolics to 4.7.0

### PR DESCRIPTION
**Pull request by shashi**
changing the syntax as seen in deprecation causes ODESystem construction to fail. This seems to be a bug in trying to automatically figuring out the independent variable.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
You would need to do it for the whole registry of them. Might be better to just yank it?

**Comment by shashi** [comment]
Wouldn't doing this in MTK prevent the others from getting the update?

**Comment by shashi** [comment]
Might be better to revert and come back once we have released a fix in MTK though...

**Comment by ChrisRackauckas** [comment]
> Wouldn't doing this in MTK prevent the others from getting the update?

No, because you would just go back one MTK version and get the Symbolics update. You have to yank it.

**Comment by ChrisRackauckas** [comment]
But did you do the yank to General?

**Pull request merged**
