### PR TITLE
Implement initialize and finalize for symbolic callbacks

### PR DESCRIPTION
**Pull request by BenChung**
## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
This looks fine but it introduces test failures?

**Comment by BenChung** [comment]
I looked at the test failures and couldn't figure out the attribution... is there a good way to tell which were broken by this PR vs. were broken beforehand?

**Comment by ChrisRackauckas** [comment]
Open a PR that just changes whitespace on README called "test master" and compare. When I was last looking, LTS was all working though, but maybe one of @AayushSabharwal's changes in SciMLBase did something there.

**Comment by AayushSabharwal** [comment]
The failures are fixed by https://github.com/SciML/SciMLBase.jl/pull/837

**Comment by BenChung** [comment]
As @AayushSabharwal says the test PR https://github.com/SciML/ModelingToolkit.jl/actions/runs/11582815665 also shows that the tests are currently broken; we could wait on his PR to merge for this one?

**Comment by ChrisRackauckas** [comment]
Master should be fixed now? Rebase.

**Pull request merged**
