### PR TITLE
fix: only evaluate required keys of varmap in `process_SciMLProblem`

### LINKED ISSUE #3153: `ifelse` in equations can produce error for `ODEProblem`
**Describe the bug 🐞**

Starting from MTK v9.47 (everything worked on v9.46) having an `ifelse(cond, x, y)` where `y` becomes complex (errors) if `cond = false`, is no longer possible in non-derivative equations (equations inlined into ODE equations with `structural_simplify`), as now an error is thrown when building the `ODEProblem`. 

It is possible to work-around when hand-coding models, but the pattern below is quite common in SBML files (and can also be worked around in SBML importers, but would be nice if possible to fix it here).

**Expected behavior**

No error when creating an `ODEProblem`.

**MRE**

```julia
using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D
@variables x(t) y(t)
@parameters c1 c2 c3
eqs = [D(x) ~ y,
       y ~ ifelse(t < c1, 0.0, (-c1 + t)^(c3))]
sps = [x, y]
ps = [c1, c2, c3]
osys = ODESystem(eqs, t, sps, ps, name = :test) |>
    structural_simplify |>
    complete
u0map = [x => 1.0]
pmap = [c1 => 5.0, c2 => 1.0, c3 => 1.2]
oprob = ODEProblem(osys, u0map, (0.0, 10.0), pmap)
```

**Error & Stacktrace ⚠️**

```julia
ERROR: DomainError with -5.0:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
Stacktrace:
  [1] throw_exp_domainerror(x::Float64)
    @ Base.Math ./math.jl:41
  [2] ^(x::Float64, y::Float64)
    @ Base.Math ./math.jl:1157
  [3] fast_substitute(expr::SymbolicUtils.BasicSymbolic{Real}, subs::Dict{Any, Any}; operator::Type)
    @ Symbolics ~/.julia/packages/Symbolics/6CYZh/src/variable.jl:585
  [4] fast_substitute
    @ ~/.julia/packages/Symbolics/6CYZh/src/variable.jl:569 [inlined]
  [5] (::Symbolics.var"#251#252"{DataType, Dict{Any, Any}, Base.RefValue{Bool}})(x::SymbolicUtils.BasicSymbolic{Real})
    @ Symbolics ~/.julia/packages/Symbolics/6CYZh/src/variable.jl:580
  [6] iterate
    @ ./generator.jl:48 [inlined]
  [7] collect_to!(dest::Vector{Real}, itr::Base.Generator{Vector{…}, Symbolics.var"#251#252"{…}}, offs::Int64, st::Int64)
    @ Base ./array.jl:838
  [8] collect_to!(dest::Vector{Bool}, itr::Base.Generator{Vector{…}, Symbolics.var"#251#252"{…}}, offs::Int64, st::Int64)
    @ Base ./array.jl:846
  [9] collect_to_with_first!(dest::Vector{…}, v1::Bool, itr::Base.Generator{…}, st::Int64)
    @ Base ./array.jl:816
 [10] _collect(c::Vector{…}, itr::Base.Generator{…}, ::Base.EltypeUnknown, isz::Base.HasShape{…})
    @ Base ./array.jl:810
 [11] collect_similar(cont::Vector{Any}, itr::Base.Generator{Vector{…}, Symbolics.var"#251#252"{…}})
    @ Base ./array.jl:709
 [12] map(f::Function, A::Vector{Any})
    @ Base ./abstractarray.jl:3371
 [13] fast_substitute(expr::SymbolicUtils.BasicSymbolic{Real}, subs::Dict{Any, Any}; operator::Type)
    @ Symbolics ~/.julia/packages/Symbolics/6CYZh/src/variable.jl:579
 [14] fast_substitute
    @ ~/.julia/packages/Symbolics/6CYZh/src/variable.jl:569 [inlined]
 [15] fixpoint_sub(x::SymbolicUtils.BasicSymbolic{Real}, dict::Dict{Any, Any}; operator::Type, maxiters::Int64)
    @ Symbolics ~/.julia/packages/Symbolics/6CYZh/src/variable.jl:520
 [16] fixpoint_sub(x::SymbolicUtils.BasicSymbolic{Real}, dict::Dict{Any, Any})
    @ Symbolics ~/.julia/packages/Symbolics/6CYZh/src/variable.jl:519
 [17] evaluate_varmap!(varmap::Dict{Any, Any})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/problem_utils.jl:309
 [18] process_SciMLProblem(constructor::Type, sys::ODESystem, u0map::Vector{…}, pmap::Vector{…}; build_initializeprob::Bool, implicit_dae::Bool, t::Float64, guesses::Dict{…}, warn_initialize_determined::Bool, initialization_eqs::Vector{…}, eval_expression::Bool, eval_module::Module, fully_determined::Bool, check_units::Bool, tofloat::Bool, use_union::Bool, u0_constructor::typeof(identity), du0map::Nothing, check_length::Bool, symbolic_u0::Bool, kwargs::@Kwargs{})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/problem_utils.jl:502
 [19] process_SciMLProblem
    @ ~/.julia/packages/ModelingToolkit/duznJ/src/systems/problem_utils.jl:410 [inlined]
 [20] (ODEProblem{…})(sys::ODESystem, u0map::Vector{…}, tspan::Tuple{…}, parammap::Vector{…}; callback::Nothing, check_length::Bool, warn_initialize_determined::Bool, eval_expression::Bool, eval_module::Module, kwargs::@Kwargs{})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:811
 [21] (ODEProblem{…})(sys::ODESystem, u0map::Vector{…}, tspan::Tuple{…}, parammap::Vector{…})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:799
 [22] (ODEProblem{true})(::ODESystem, ::Vector{Pair{Num, Float64}}, ::Vararg{Any}; kwargs::@Kwargs{})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:786
 [23] (ODEProblem{true})(::ODESystem, ::Vector{Pair{Num, Float64}}, ::Vararg{Any})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:785
 [24] ODEProblem(::ODESystem, ::Vector{Pair{Num, Float64}}, ::Vararg{Any}; kwargs::@Kwargs{})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:775
 [25] ODEProblem(::ODESystem, ::Vector{Pair{Num, Float64}}, ::Vararg{Any})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:774
 [26] top-level scope
    @ ~/Dropbox/PhD/tmp/test_fail/MVE.jl:14
Some type information was truncated. Use `show(err)` to see complete types.
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `~/Dropbox/PhD/tmp/test_fail/Project.toml`
  [961ee093] ModelingToolkit v9.48.0
  [43230ef6] OrdinaryDiffEqRosenbrock v1.2.0
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
Status `~/Dropbox/PhD/tmp/test_fail/Manifest.toml`
  [47edcb42] ADTypes v1.9.0
  [1520ce14] AbstractTrees v0.4.5
  [7d9f7c33] Accessors v0.1.38
  [79e6a3ab] Adapt v4.1.0
  [66dad0bd] AliasTables v1.1.3
  [ec485272] ArnoldiMethod v0.4.0
  [4fba245c] ArrayInterface v7.16.0
  [4c555306] ArrayLayouts v1.10.4
  [e2ed5e7c] Bijections v0.1.9
  [62783981] BitTwiddlingConvenienceFunctions v0.1.6
  [8e7c35d0] BlockArrays v1.1.1
  [2a0fbf3d] CPUSummary v0.2.6
  [00ebfdb7] CSTParser v3.4.3
  [d360d2e6] ChainRulesCore v1.25.0
  [fb6a15b2] CloseOpenIntervals v0.1.13
  [861a8166] Combinatorics v1.0.2
  [a80b9123] CommonMark v0.8.15
  [38540f10] CommonSolve v0.2.4
  [bbf7d656] CommonSubexpressions v0.3.1
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [34da2185] Compat v4.16.0
  [b152e2b5] CompositeTypes v0.1.4
  [a33af91c] CompositionsBase v0.1.2
  [2569d6c7] ConcreteStructs v0.2.3
  [187b0558] ConstructionBase v1.5.8
  [adafc99b] CpuId v0.3.1
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [864edb3b] DataStructures v0.18.20
  [e2d170a0] DataValueInterfaces v1.0.0
  [2b5f629d] DiffEqBase v6.158.3
  [459566f4] DiffEqCallbacks v4.0.0
  [77a26b50] DiffEqNoiseProcess v5.23.0
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.6.16
  [8d63f2c5] DispatchDoctor v0.4.16
  [31c24e10] Distributions v0.25.112
  [ffbed154] DocStringExtensions v0.9.3
  [5b8099bc] DomainSets v0.7.14
  [7c1d4256] DynamicPolynomials v0.6.0
  [06fc5a27] DynamicQuantities v1.1.0
  [4e289a0a] EnumX v1.0.4
  [f151be2c] EnzymeCore v0.8.4
  [e2ba6199] ExprTools v0.1.10
⌅ [6b7a57c9] Expronicon v0.8.5
  [7034ab61] FastBroadcast v0.3.5
  [9aa1b823] FastClosures v0.3.2
  [29a986be] FastLapackInterface v2.0.4
  [a4df4552] FastPower v1.1.0
  [1a297f60] FillArrays v1.13.0
  [64ca27bc] FindFirstFunctions v1.4.1
  [6a86dc24] FiniteDiff v2.26.0
  [1fa38f19] Format v1.3.7
  [f6369f11] ForwardDiff v0.10.36
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [d9f16b24] Functors v0.4.12
⌅ [46192b85] GPUArraysCore v0.1.6
  [c27321d9] Glob v1.3.1
  [86223c79] Graphs v1.12.0
  [3e5b6fbb] HostCPUFeatures v0.1.17
  [34004b35] HypergeometricFunctions v0.3.24
  [615f187c] IfElse v0.1.1
  [d25df0c9] Inflate v0.1.5
  [18e54dd8] IntegerMathUtils v0.1.2
  [8197267c] IntervalSets v0.7.10
  [3587e190] InverseFunctions v0.1.17
  [92d709cd] IrrationalConstants v0.2.2
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.6.1
  [98e50ef6] JuliaFormatter v1.0.62
  [ccbc3e58] JumpProcesses v9.14.0
  [ef3ab10e] KLU v0.6.0
  [ba0b0d4f] Krylov v0.9.7
  [b964fa9f] LaTeXStrings v1.4.0
  [23fbe1c1] Latexify v0.16.5
  [10f19ff3] LayoutPointers v0.1.17
  [5078a376] LazyArrays v2.2.1
  [87fe0de2] LineSearch v0.1.4
  [d3d80556] LineSearches v7.3.0
  [7ed4a6bd] LinearSolve v2.36.1
  [2ab3a3ac] LogExpFunctions v0.3.28
  [bdcacae8] LoopVectorization v0.12.171
  [d8e11817] MLStyle v0.4.17
  [1914dd2f] MacroTools v0.5.13
  [d125e4d3] ManualMemory v0.1.8
  [bb5d69b7] MaybeInplace v0.1.4
  [e1d29d7a] Missings v1.2.0
  [961ee093] ModelingToolkit v9.48.0
  [46d2c3a1] MuladdMacro v0.2.4
  [102ac46a] MultivariatePolynomials v0.5.7
  [d8a4904e] MutableArithmetics v1.5.2
  [d41bc354] NLSolversBase v7.8.3
  [77ba4419] NaNMath v1.0.2
  [8913a72c] NonlinearSolve v3.15.1
  [6fe1bfb0] OffsetArrays v1.14.1
  [429524aa] Optim v1.9.4
  [bac558e1] OrderedCollections v1.6.3
  [bbf590c4] OrdinaryDiffEqCore v1.9.0
  [4302a76b] OrdinaryDiffEqDifferentiation v1.1.0
  [43230ef6] OrdinaryDiffEqRosenbrock v1.2.0
  [90014a1f] PDMats v0.11.31
  [65ce6f38] PackageExtensionCompat v1.0.2
  [d96e819e] Parameters v0.12.3
  [e409e4f3] PoissonRandom v0.4.4
  [f517fe37] Polyester v0.7.16
  [1d0040c9] PolyesterWeave v0.2.2
  [85a6dd25] PositiveFactorizations v0.2.4
  [d236fae5] PreallocationTools v0.4.24
  [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [27ebfcd6] Primes v0.5.6
  [43287f4e] PtrArrays v1.2.1
  [1fd47b50] QuadGK v2.11.1
  [74087812] Random123 v1.7.0
  [e6cf234a] RandomNumbers v1.6.0
  [3cdcf5f2] RecipesBase v1.3.4
  [731186ca] RecursiveArrayTools v3.27.0
  [f2c3362d] RecursiveFactorization v0.2.23
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.0
  [ae5879a3] ResettableStacks v1.1.1
  [79098fc4] Rmath v0.8.0
  [7e49a35a] RuntimeGeneratedFunctions v0.5.13
  [94e857df] SIMDTypes v0.1.0
  [476501e8] SLEEFPirates v0.6.43
  [0bca4576] SciMLBase v2.57.1
  [19f34311] SciMLJacobianOperators v0.1.0
  [c0aeaf25] SciMLOperators v0.3.11
  [53ae85a6] SciMLStructures v1.5.0
  [efcf1570] Setfield v1.1.1
  [727e6d20] SimpleNonlinearSolve v1.12.3
  [699a6c99] SimpleTraits v0.9.4
  [ce78b400] SimpleUnPack v1.1.0
  [a2af1166] SortingAlgorithms v1.2.1
  [9f842d2f] SparseConnectivityTracer v0.6.8
  [47a9eef4] SparseDiffTools v2.23.0
  [0a514795] SparseMatrixColorings v0.4.8
  [e56a9233] Sparspak v0.3.9
  [276daf66] SpecialFunctions v2.4.0
  [aedffcd0] Static v1.1.1
  [0d7ed370] StaticArrayInterface v1.8.0
  [90137ffa] StaticArrays v1.9.8
  [1e83bf80] StaticArraysCore v1.4.3
  [10745b16] Statistics v1.11.1
  [82ae8749] StatsAPI v1.7.0
  [2913bbd2] StatsBase v0.34.3
  [4c63d2b9] StatsFuns v1.3.2
  [7792a7ef] StrideArraysCore v0.5.7
  [2efcf032] SymbolicIndexingInterface v0.3.33
  [19f23fe9] SymbolicLimits v0.2.2
  [d1185830] SymbolicUtils v3.7.2
  [0c5d862f] Symbolics v6.16.0
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.0
  [8ea1fca8] TermInterface v2.0.0
  [1c621080] TestItems v1.0.0
  [8290d209] ThreadingUtilities v0.5.2
  [a759f4b9] TimerOutputs v0.5.25
  [0796e94c] Tokenize v0.5.29
  [d5829a12] TriangularSolve v0.2.1
  [410a4b4d] Tricks v0.1.9
  [781d530d] TruncatedStacktraces v1.4.0
  [5c2747f8] URIs v1.5.1
  [3a884ed6] UnPack v1.0.2
  [1986cc42] Unitful v1.21.0
  [a7c27f48] Unityper v0.1.6
  [3d5dd08c] VectorizationBase v0.21.70
  [19fa3120] VertexSafeGraphs v0.2.0
  [1d5cc7b8] IntelOpenMP_jll v2024.2.1+0
  [856f044c] MKL_jll v2024.2.0+0
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [f50d1b31] Rmath_jll v0.5.1+0
  [1317d2d5] oneTBB_jll v2021.12.0+0
  [0dad84c5] ArgTools v1.1.2
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [4af54fe1] LazyArtifacts v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.11.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [a63ad114] Mmap v1.11.0
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.11.0
  [de0858da] Printf v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [1a1011a3] SharedArrays v1.11.0
  [6462fe0b] Sockets v1.11.0
  [2f01184e] SparseArrays v1.11.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test v1.11.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] LibCURL_jll v8.6.0+0
  [e37daf67] LibGit2_jll v1.7.2+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.6+0
  [14a3606d] MozillaCACerts_jll v2023.12.12
  [4536629a] OpenBLAS_jll v0.3.27+1
  [05823500] OpenLibm_jll v0.8.1+2
  [bea87d4a] SuiteSparse_jll v7.7.0+0
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.11.0+0
  [8e850ede] nghttp2_jll v1.59.0+0
  [3f19e933] p7zip_jll v17.4.0+2
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
```

  - Output of `versioninfo()`

```julia
Julia Version 1.11.1
Commit 8f5b7ca12ad (2024-10-16 10:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, tigerlake)
Threads: 4 default, 0 interactive, 2 GC (on 8 virtual cores)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

**Additional context**

The following with `ifelse` in the ODE equations works:

```julia
using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D
@variables x(t) y(t)
@parameters c1 c2 c3
eqs = [D(x) ~ y,
       y ~ ifelse(t < c1, 0.0, (-c1 + t)^(c3))]
sps = [x, y]
ps = [c1, c2, c3]
osys = ODESystem(eqs, t, sps, ps, name = :test) |>
    structural_simplify |>
    complete
u0map = [x => 1.0]
pmap = [c1 => 5.0, c2 => 1.0, c3 => 1.2]
oprob = ODEProblem(osys, u0map, (0.0, 10.0), pmap)
```

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Close #3153 

## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by isaacsas** [comment]
Has this been tested against catalyst to ensure it won’t break stuff? Note that CI here is not currently doing such a test.

**Comment by isaacsas** [comment]
(Because of BifurcationKit not getting updated yet.)

**Comment by ChrisRackauckas** [comment]
Why wouldn't the downstream test be sufficient on all?

Also, Catalyst doesn't use this function at all https://github.com/search?q=repo%3ASciML%2FCatalyst.jl%20evaluate_varmap!&type=code

**Comment by AayushSabharwal** [comment]
Additionally, this was the behavior of the `*Problem` constructors before the cleanup anyway. I changed to evaluating the entire varmap because it seemed cleaner to do it once and use the "finalized" varmap everywhere but didn't know of the edge case in the linked issue.

**Comment by AayushSabharwal** [comment]
I'll test master against catalyst, though, because of #3155

**Comment by isaacsas** [comment]
@ChrisRackauckas Just look at the integration test on Catalyst here — it didn’t actually run due to the bifurcation kit version incompatibility. 

I will remove that extension from Catalyst later today until someone can update it (to get downstream testing here working again). More generally though, this issue is part of why I wanted to move extensions to separate libs.

**Comment by isaacsas** [comment]
@AayushSabharwal ok, thanks for explaining. Just didn’t want to break the conservation law handling in problem construction suddenly. If this was the old behavior it should be fine.

**Comment by AayushSabharwal** [comment]
I can't get Catalyst tests to run. Artificially lowering `BifurcationKit` compat doesn't work, and neither does removing the extension altogether.

**Comment by isaacsas** [comment]
Ok, I’ll see what is going on when I’m at work later, and get Catalyst master working with downstream here again. I’m not sure why removing BifurcationKit from the Project.toml and testing isn’t sufficient.

**Comment by ChrisRackauckas** [comment]
Okay, since Catalyst does not use this function and it's reverting to an older behavior, I'm going to merge. I'm confused why Catalyst is brought up here in the first place, though we should fix that extension, I do not understand why the concern on a function it doesn't use?

**Comment by isaacsas** [comment]
Every *Problem is built via that function. I was concerned changing the initialization in this way could break something we rely on (like conserved constant initialization). if it is the old behavior it should be fine.

**Pull request merged**
