### PR TITLE
Add Conductor.jl as a downstream test

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by anandijain** [comment]
it'd probably be fine to skip conductor on LTS/1.6, is that possible?

**Comment by ChrisRackauckas** [comment]
@wsphillips what's the issue with v1.6? It would be difficult to section that out.

**Comment by anandijain** [comment]
its just kwargs `ERROR: LoadError: LoadError: syntax: invalid assignment location "; interval, duration, delay, npulses, offset, amplitude" around /home/runner/work/ModelingToolkit.jl/ModelingToolkit.jl/downstream/src/stimulus.jl:24`

https://github.com/SciML/ModelingToolkit.jl/actions/runs/3578134519/jobs/6017939231

**Comment by wsphillips** [comment]
I'm using destructuring syntax. I guess I can go back to use `@unpack` or similar

**Pull request closed without merging**
