### PR TITLE
Add back rank2 (highest diffed variables) in alias elimination

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by YingboMa** [comment]
We want to pivot on highest differentiated variables to eliminate/simplify any equation that is not structurally visible.

**Comment by staticfloat** [comment]
This looks good in our tests!

**Comment by staticfloat** [comment]
@YingboMa we've got the MSL tests working more or less with this branch, so we're pretty happy with it.  It looks like there's a failure on a `dummy_derivatives()` test in `linearize.jl`, though.

**Comment by YingboMa** [comment]
How do you know it's a dummy_derivatives test?

**Comment by staticfloat** [comment]
> How do you know it's a dummy_derivatives test?

Because it was [this test](https://github.com/SciML/ModelingToolkit.jl/blob/master/test/linearize.jl#L229), and at the top of that file, it [mentions dummy_derivatives](https://github.com/SciML/ModelingToolkit.jl/blob/master/test/linearize.jl#L182).

**Comment by YingboMa** [comment]
Ah, OK. I thought I missed something. It's a pretty complicated test, and failed for a different reason.

**Pull request merged**
