### PR TITLE
support symbolic parameters at problem level

### LINKED ISSUE #991: Simulation fails when using parameters in the initial value map
Hi, 

Version:
[961ee093] ModelingToolkit v5.16.0

I have the following Lotka Volterra model:
```
#= Lotka-Volterra, John Tinnerholm=#
using ModelingToolkit    
using DiffEqBase    
using DifferentialEquations    
function LotkaVolterraSimulate(tspan = (0.0, 100.0))                
  pars = @parameters(begin             
                     alpha
                     x0
                     gamma
                     y0
                     delta
                     beta            
                     t
                     end)        
  vars = @variables(begin             
                    y(t)
                    x(t)                    
                    end)        
  der = Differential(t)        
  eqs = [der(y) ~ (delta * x - gamma) * y, der(x) ~ (alpha - beta * y) * x]        
  nonLinearSystem =
    ODESystem(eqs, t, vars, pars, name = :($(Symbol("LotkaVolterra"))))        
  pars = [
    alpha => 0.1,
    x0 => 10.0,
    gamma => 0.4,
    y0 => 10.0,
    delta => 0.02,
    beta => 0.02,
    t => tspan[1],
  ]        
  initialValues = [
    y => 10.0,
    x => 10.0
  ]        
  firstOrderSystem = ModelingToolkit.ode_order_lowering(nonLinearSystem)        
  reducedSystem = dae_index_lowering(firstOrderSystem)        
  problem = ODEProblem(reducedSystem, initialValues, tspan, pars)
  return problem
end
```

This works and simulates just fine! 
image

However, if I use the parameters for the initial values that is 
```
  initialValues = [
    y => x0,
    x => y0
  ]        
```
and running it with:

`sol = solve(LotkaVolterraSimulate(), Tsit5())
`
I get the following error: 

```
ERROR: LoadError: StackOverflowError:
Stacktrace:
 [1] recursive_unitless_bottom_eltype(a::Type{Any}) (repeats 79984 times)
   @ RecursiveArrayTools ~\.julia\packages\RecursiveArrayTools\K3lTR\src\utils.jl:86
in expression starting at C:<Path>\LotkaVolterra.jl:40
```

Is this intended or a bug? 

Cheers,
John

### PR DESCRIPTION
**Pull request by pepijndevos**
fix #991

### CODE REVIEW

**Comment by pepijndevos** [comment]
Yea uh that doesn't really work for initial conditions passed as an array.

**Comment by pepijndevos** [comment]
I mean you could just turn them into a map, but I'm not convinced this is the right approach.

**Comment by ChrisRackauckas** [comment]
oh the issue is that the initial conditions are an array not a vector?

**Comment by pepijndevos** [comment]
Well no just that my quick fix only works when `parammap` amd `u0map` are a dict or list of pairs, rather than a flat array.

**Comment by pepijndevos** [comment]
If you set initial conditions to `[10]` rather than `[x0 => 10]` you can't really pass that as a dict to defaults.
Of course you can do something like `Dict(zip(states(sys), parammap)` but seems like a bit ugly, so we should first answer the question if this is the correct approach.

**Comment by ChrisRackauckas** [comment]
isa Dict || eltype isa Pair?

**Comment by pepijndevos** [comment]
```julia
eltype(parammap)
Pair{Num, Float64}
eltype(parammap) isa Pair
false
```

**Comment by ChrisRackauckas** [comment]
`eltype(parammap) <: Pair`

**Comment by pepijndevos** [comment]
huh, I guess I never really thought about the exact difference between `isa` and `<:`. Well anyway I think it should work now.

**Pull request merged**
