### PR TITLE
Restore error when unknowns in the initialization system don't have guesses 

### PR DESCRIPTION
**Pull request by hersle**
Another attempt to fix https://github.com/SciML/ModelingToolkit.jl/issues/2873 in a simpler way; supersedes #2874.

## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API

### CODE REVIEW

**Comment by hersle** [comment]
Seems weird that just disabling one early-return optimization causes one test to fail. Looks like there is just a `t` that is not substituted. Have DDEs just not gotten the non-autonomous treatment?

**Comment by ChrisRackauckas** [comment]
>  Looks like there is just a t that is not substituted. Is there something DDE-specific going on here, or have DDEs just not gotten the non-autonomous treatment?

DDEs naturally do a bit more with `t` since it's common to have say `x(t - tau)`, or `x(t - y(t))`. I wonder if those cases trip it up.

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
This looks good to go though? Just the latexify regression test needs an update, but I'd be fine handling that after merge.

**Comment by hersle** [comment]
Yes, that's what I realized. It seems that DDEs relied on the early return, which is why they pass `tofloat = false` in the first place.

I think it's good to merge, yes.

**Comment by ChrisRackauckas** [comment]
Thanks for seeing this one through. I hadn't found the time to do it since it was pretty non-trivial, but in the end I think you figured out a good solution.

**Pull request merged**
