### PR TITLE
Partial State Selection

### PR DESCRIPTION
**Pull request by Keno**
This implements the basic outline of partial state selection.
It is functional and resolves the example in #988, but we do not
currently implement any tearing priorities or handling of linear
subsystems, so it's pretty easy for state selection to end up
selecting states that are singular.

Note this currently includes commits from https://github.com/SciML/ModelingToolkit.jl/pull/1355, since
it builds on top, but I can't use that as a base branch because it's not on this repo. Once that is merged,
I'll rebase this. The relevant changes are in the final commit.

### CODE REVIEW

**Comment by YingboMa** [comment]
@isaacsas It seems like Catalyst uses MTK internal `initialize_system_structure`. Could you update Catalyst so that it doesn't rely on it?

**Comment by isaacsas** [comment]
> @isaacsas It seems like Catalyst uses MTK internal `initialize_system_structure`. Could you update Catalyst so that it doesn't rely on it?

Sure. Looks like we use it to determine if an equation is a diff eq (vs. algebraic). Is there a recommended alternative to check if an equation is a diff eq now?

**Comment by YingboMa** [comment]
Maybe just iterate over `eq.lhs` and check all of them are in the form of `D(x)`?

**Comment by YingboMa** [comment]
@isaacsas I will merge this PR for now and not release a new version of MTK until Catalyst updates accordingly.

**Comment by isaacsas** [comment]
I’ll ping you once a new Catalyst release is out with the fix.

**Comment by isaacsas** [comment]
New Catalyst release is out.

**Pull request merged**
