### PR TITLE
replace GenearlizedGenerated with RuntimeGeneratedFunctions

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
@c42f do you know what's going on with this?

```julia
Direct Usage Test: Error During Test at C:\Users\accou\.julia\packages\SafeTestsets\A83XK\src\SafeTestsets.jl:25
  Got exception outside of a @test
  LoadError: LoadError: UndefVarError: ModelingToolkit not defined
  Stacktrace:
   [1] top-level scope
   [2] (::RuntimeGeneratedFunctions.RuntimeGeneratedFunction{ModelingToolkit.var"#_RuntimeGeneratedFunctions_ModTag",(0xba, 0xf5, 0x1a, 0x9a, 0x7c, 0x92, 0xf6, 0x80, 0xaf, 0x8a, 0x08, 0x9b, 0xa4, 0xb4, 0x2f, 0xfd, 0x8c, 0xa5, 0x86, 0x6e, 0x1c, 0xa8, 0x5b, 0xd8, 0x19, 0x7b, 0xef, 0x1a, 0x85, 0x4e, 0x0f, 0xd1, 0x31, 0x97, 0xf8, 0x2a, 0x7a, 0x5b, 0x7d, 0x10, 0xf0, 0x86, 0x31, 0xb9, 0xb9, 0x54, 0x34, 0x8e, 0x44, 0x4a, 0xad, 0x2a, 0xff, 0x3c, 0x59, 0x47, 0xf9, 0xf2, 0x8b, 0xcd, 0xb6, 0xbb, 0x61, 0x24),(Symbol("##MTKArg#5640"), Symbol("##MTKArg#5641"))})(::Array{Float64,1}, ::Array{Float64,1}) at C:\Users\accou\.julia\packages\RuntimeGeneratedFunctions\WBFJ5\src\RuntimeGeneratedFunctions.jl:60
   [3] test_worldage() at C:\Users\accou\.julia\dev\ModelingToolkit\test\direct.jl:121
   [4] top-level scope at C:\Users\accou\.julia\dev\ModelingToolkit\test\direct.jl:124
   [5] include(::Function, ::Module, ::String) at .\Base.jl:380
   [6] include at .\Base.jl:368 [inlined]
   [7] include(::String) at C:\Users\accou\.julia\packages\SafeTestsets\A83XK\src\SafeTestsets.jl:23
   [8] top-level scope at C:\Users\accou\.julia\dev\ModelingToolkit\test\runtests.jl:7
   [9] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Test\src\Test.jl:1115
   [10] top-level scope at C:\Users\accou\.julia\dev\ModelingToolkit\test\runtests.jl:7
   [11] eval(::Module, ::Any) at .\boot.jl:331
   [12] top-level scope at C:\Users\accou\.julia\packages\SafeTestsets\A83XK\src\SafeTestsets.jl:23
   [13] include(::String) at .\client.jl:457
   [14] top-level scope at none:6
   [15] eval(::Module, ::Any) at .\boot.jl:331
   [16] exec_options(::Base.JLOptions) at .\client.jl:272
   [17] _start() at .\client.jl:506
  in expression starting at <macrocall>:0
  in expression starting at C:\Users\accou\.julia\dev\ModelingToolkit\test\direct.jl:124
```

### CODE REVIEW

**Comment by c42f** [comment]
Could it be to do with the scope of symbol resolution within the `RuntimeGeneratedFunction`?

For example in the following, `y` is not found because the body looks up symbols within `RuntimeGeneratedFunctions` rather than module `M`?

```julia
julia> module M
       using RuntimeGeneratedFunctions
       y = 10
       f = @RuntimeGeneratedFunction(:(x->x+y))
       end
WARNING: replacing module M.
Main.M

julia> M.f(1)
ERROR: UndefVarError: y not defined
Stacktrace:
 [1] macro expansion at ./REPL[4]:4 [inlined]
 [2] macro expansion at /home/chris/.julia/packages/RuntimeGeneratedFunctions/WBFJ5/src/RuntimeGeneratedFunctions.jl:68 [inlined]
 [3] macro expansion at ./none:0 [inlined]
 [4] generated_callfunc at ./none:0 [inlined]
 [5] (::RuntimeGeneratedFunctions.RuntimeGeneratedFunction{Main.M.var"#_RuntimeGeneratedFunctions_ModTag",(0x33, 0x71, 0x28, 0x74, 0xd2, 0x8f, 0x5d, 0xc2, 0xbf, 0xc7, 0x49, 0x99, 0x6c, 0xda, 0x14, 0x12, 0x12, 0xae, 0x5d, 0x99, 0xc3, 0x36, 0xa6, 0x18, 0x1c, 0x68, 0x17, 0x88, 0xc2, 0x67, 0x96, 0x4d, 0xc8, 0x45, 0xf2, 0xec, 0xfe, 0x0a, 0xc6, 0x55, 0x9c, 0xc7, 0x2f, 0x84, 0x2a, 0x91, 0x4f, 0xed, 0x71, 0x83, 0x0a, 0x8c, 0x2f, 0x81, 0xf5, 0xe0, 0xa2, 0xc4, 0x68, 0x1a, 0xba, 0x63, 0x01, 0x3d),(:x,)})(::Int64) at /home/chris/.julia/packages/RuntimeGeneratedFunctions/WBFJ5/src/RuntimeGeneratedFunctions.jl:60
 [6] top-level scope at REPL[5]:1
```

**Comment by ChrisRackauckas** [comment]
Yeah, that would do it. It's a macro so it should in theory be able to be ran in the caller's module, right?

**Comment by c42f** [comment]
Yeah it does know about the caller's module (that's indeed the point of the macro), but the `@generated` function which emits the body lives within `RuntimeGeneratedFunctions`. So all symbols are looked up relative to that which is pretty broken.

I think I know how to fix this — we can make a unique method of `generated_callfunc` defined in each user's module as part of the setup. We already have a handy `moduletag` to dispatch on so that should be easy. The annoying bit is avoiding the world age issues; we may need the user to call an init macro at top level. (Alternatively, we could perform source code analysis to look for global symbols and make sure they're qualified to the user's module. But that's reproducing a large part of lowering and I'd rather let the compiler do that for us.)

Oh, another idea might be to call `Meta.lower(users_module, ex)` explicitly within our module and emit a `CodeInfo` from the generated function?

Can't do the fix right away — I'm away from the computer for a few days (starting now-ish).

**Comment by ChrisRackauckas** [comment]
No worries, have a nice vacation, I'll bother you next week 😆

**Comment by c42f** [comment]
Hopefully https://github.com/SciML/RuntimeGeneratedFunctions.jl/pull/12 will fix this.

**Pull request merged**
