### PR TITLE
Add default parameter argument to the PDESystem

### PR DESCRIPTION
**Pull request by ashutosh-b-b**
Needed for SciML/NeuralPDE.jl#256

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
@AlCap23 do you know what the downstream issue is? It's not related to the PR so it's kind of odd.

**Comment by AlCap23** [comment]
I think its due to the recent updates with the getters / setters and maybe some changes within symbolic utils. I will have a look now and see whats causing this, since the PRs in DataDriven seems to be fine. But this PR has nothing to do with it :+1:

**Comment by AlCap23** [comment]
Quick update: This is related to 

```julia
@variables x y
a = Num[x;x;y;x;y] 
unique(a) # Works
unique!(a) # Errors with
```

```julia
unique!(a)
ERROR: TypeError: non-boolean (Num) used in boolean context
Stacktrace:
 [1] issorted(::Array{Num,1}, ::Base.Order.ForwardOrdering) at ./sort.jl:62
 [2] #issorted#1 at ./sort.jl:91 [inlined]
 [3] issorted at ./sort.jl:91 [inlined]
 [4] unique!(::Array{Num,1}) at ./set.jl:341
 [5] top-level scope at none:1
```

**Comment by ChrisRackauckas** [comment]
Interesting. Open an issue. I haven't seen that before. @shashi might know

**Comment by AlCap23** [comment]
I found the real error. Sorry. It was hidden in `create_linear_independent_eqs`, which returned `Vector{Any}` instead of `Num` .

**Pull request merged**
