### PR TITLE
Add the dummy derivative pass

### PR DESCRIPTION
**Pull request by YingboMa**
```julia
julia> u0 = [
         D(x)    => 0.0,
         D(y)    => 0.0,
         x       => sqrt(2)/2,
         y       => sqrt(2)/2,
         T       => 0.0
       ];

julia> p = [
           L => 1.0,
           g => 9.8
       ];

julia> equations(pendulum2)
3-element Vector{Equation}:
 Differential(t)(Differential(t)(x(t))) ~ T(t)*x(t)
 Differential(t)(Differential(t)(y(t))) ~ T(t)*y(t) - g
 0 ~ x(t)^2 + y(t)^2 - (L^2)

julia> prob_auto = DAEProblem(structural_simplify(pendulum2),zeros(length(u0)),u0,(0.0,10.0),p);

julia> sol = solve(prob_auto, DFBDF());
```

pendulum_dd_mtk

The solver would error out if I integrate it for longer. Since `x''(t) == d/dt x'(t)` may not hold if `x''` is a dummy derivative, we might have to implement manifold projection for DAE solvers to ensure that the dummy derivatives don't drift too much.

This PR fixes https://github.com/SciML/ModelingToolkit.jl/issues/1537 and https://github.com/SciML/ModelingToolkit.jl/issues/1516

### CODE REVIEW

**Comment by YingboMa** [comment]
The ModelingToolkitStandardLibrary test failure is actually a good thing. It's now detecting some ODEs are actually implicit DAEs so MTK rejects to build the wrong problem. We need better implicit DAE handling to make ModelingToolkitStandardLibrary pass again.

**Comment by ChrisRackauckas** [comment]
> The ModelingToolkitStandardLibrary test failure is actually a good thing. It's now detecting some ODEs are actually implicit DAEs so MTK rejects to build the wrong problem. We need better implicit DAE handling to make ModelingToolkitStandardLibrary pass again.

How were they handled before?

**Comment by YingboMa** [comment]
@ValentinKaisermayer @ChrisRackauckas can we mark the failing tests ModelingToolkitStandardLibrary for now? Writing implicit to semi-implicit pass will take a while.

**Comment by ValentinKaisermayer** [comment]
> The ModelingToolkitStandardLibrary test failure is actually a good thing. It's now detecting some ODEs are actually implicit DAEs so MTK rejects to build the wrong problem. We need better implicit DAE handling to make ModelingToolkitStandardLibrary pass again.

Maybe such a test case should be part of MTK.

**Comment by YingboMa** [comment]
> Maybe such a test case should be part of MTK.

Yeah, do you want to make a PR? You can put the definitions in examples, and add the tests in `test/state_selection.jl`

**Pull request merged**
