### PR TITLE
adding defaults to ReactionSystem constructors

### PR DESCRIPTION
**Pull request by anandijain**
I'm not sure if I need to do any scaling of defaults during conversion

### CODE REVIEW

**Review by isaacsas — APPROVED** [review]

**Comment by isaacsas** [comment]
Looks ok to me. I guess we merge here and then retest the Catalyst PR once there is a new release. @ChrisRackauckas that ok?

**Comment by isaacsas** [comment]
@anandijain can you update the direct problem constructors too, which also call convert? I missed those.

**Review by ChrisRackauckas — APPROVED** [review]
looks good to me.

**Comment by isaacsas** [comment]
I’ll merge once those last updates are in and tests pass.

**Comment by ChrisRackauckas** [comment]
wait, isn't `defaults` usually a keyword argument in system constructors? It should match the format of the others.

**Comment by anandijain** [comment]
i need to merge u0 and default_u0, similarly for `p` 
where u0 and p that are passed as args are preferred

**Comment by isaacsas** [comment]
Just mimic ODESystem.

**Comment by anandijain** [comment]
would appreciate a sanity check, but I think it works as it is now, see the tests I added. it seems like defaults get handled just fine as is

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by isaacsas** [comment]
Duh, yeah it just gets passed through as a kwarg.

**Comment by ChrisRackauckas** [comment]
Why is Catalyst failing?

**Comment by anandijain** [comment]
it uses the direct rxnsys constructors so its missing that last Dict() arg. see that pr to see why

**Comment by anandijain** [comment]
we are about to walk home, would u mind patch versioning and rerunning the catalyst pr test

**Comment by ChrisRackauckas** [comment]
already started.

**Pull request merged**
